### ISSUE TITLE
Change language via system settings

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#111]
OpenSlides admins should change the language of an event via the OpenSlides configuration tab (system settings). Currently it's possible only via the value of "LANGUAGE_CODE" in settings.py.

**Comment by frederikheld** [comment]
This is a very old issue but I stumbled upon it when I looked for a way to set the language for all users. @ostcar I'm gonna answer your question about the advantage in this feature.

When I'm moderating a gathering of a small club of non-techies who all speak the same language:

1. often the users themselves don't understand why their browser is displaying all websites in the "wrong" language (aka not their native language) neither do they know how to change it.* I can't do user support during an event, but I could avoid this issue upfront by configuring OpenSlides to use the "right" language for everyone.

2. if I moderate a event with people who never used OpenSlides, I need to explain them where they have to click to get to agenda/motions/etc. This needs to be in the language in which we moderate the event and this needs to be in the same language for all users. Because otherwise chaos ensues.

The perfect solution would be if I could set a default language through settings.py and OpenSlides would give advanced usres the option to manually change it to the language of their choice through the web interface.

I'm not a fan of auto-detection tbh as I find it very confusing. Not all websites use it, so if you want to change the language, you can never be certain if the site itself has a language setting, if I need to change the browser setting or if there's just no way to change it.

Sorry for grave digging :-P

Cheers
Fred
