### ISSUE TITLE
Use list of speakers on every slide, not only agenda slides.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1280]
See request on German mailing list:

>> Zur Rednerliste: Redner können nur zu originären Tagesordnungspunkten
>> oder zu Tagesordnungspunkten, die mit einem Antrag oder einer Wahl
>> verbunden sind, geführt und damit angezeigt werden. So ist das
>> derzeitige Konzept. Das ist aber nicht in Stein gemeißelt. Wie wäre denn
>> eure Vorstellung? Soll zu jeder möglichen Folie eine Rednerliste geführt
>> werden können?
> 
> ja, bei allen Darstellungsmöglichkeiten des Projektors. Der bisherige
> Ansatz der Rednerliste orientiert sich vermutlich an der
> Versammlungsfunktion. Dies wärei für die Landes- und
> Bundesmitgliederversammlungen sicher auch die benötigte Funktion.
> 
> Die Überlegungen ergaben sich, weil wir OS am WE erst einmal im
> Arbeitskreis Bürgerbegehren im Meeting testen. Bei diesem
> Versammlungstyp würde eine Verknüpfung der Projektorsicht mit der
> Rednerliste den Ablauf möglicherweise vereinfachen können. Wenn jeder
> sich aktuell und transparent auf die Rednerliste in die Charts
> einblenden kann, würde das Sytem selber die Moderation übernehmen können
> und den Ablauf verkürzen.
> Bei Bürgerbegehrens- und Beteiligungsprojekten bei denen häufig erst
> einmal keine formalen Strukturen bestehen, könnte diese sich
> selbstorgnisierende softwaregesstützte Funktion hilfreich sein.

**Comment by emanuelschuetze** [comment]
Similar feature request from a customer:
A manager wants to create a list of speakers __for each__ motion __without__ adding motion (as sub item) to the agenda. Required is that each motion has its own list of speakers so that you can archive these lists and use the lists later for protocol. A global list of speakers could be useful additional for meetings without special formal agenda or motions (like initial comment) but this does not help in this special case. I prefer that we discuss (and maybe implement) a new list of speakers concept for 2.0.
@ostcar Any idea how can we realize the requirements?

**Comment by emanuelschuetze** [comment]
With PR #1659 we have a generic solutions for related agenda items - each item object (e.g. custom slide, motion, assignment) has its own list of speakers.
Some general template improvements comes in the next weeks. But this special issue can be closed.
