### ISSUE TITLE
Update portable to use Python 3 only

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1330]

**Comment by emanuelschuetze** [comment]
@andkit Sorry for my late reply! I just testet your branch. Generally, it runs good. I tested successfully:
 * start server with default server settings / with other port number, and with/without open browser
 * backup database function
 * sync database
 * reset admin

But I found some (minor) issues:
 * plugin dectection does not work
 * a black cmd window is starting in background if you start the GUI (openslides.exe). Please hide this cmd window!
 * GUI crashed if you start and stop server and than quit window ("x")
 * after first start of openslides.exe an unattractive directory "openslides\__pycache__" is created which contains "settings.cpython-34.pyc; Can you please move/hide this file from OpenSlides user data directory?
 * Update year in credits: 2014 -> 2015

Question:
What do you mean with "Update code for msvcrt bundling in prepare_portable"? Is there something still to do?

Maybe you can create a pull request while our OpenSlides developer meeting next weekend? ;-)
Thanks in advance!

**Comment by emanuelschuetze** [comment]
For the record: I testet with wxPython-Phoenix 3.0.3.dev78356

**Comment by andkit** [comment]
@emanuelschuetze Ok so apart from the crash and the (expectedy) non-working plugin detection there where no major issues - so far so good

I'll look into fixing the problems you raised when I find some time, but that may be a while for me as well (this weekend is already planned, next one depends on some stuff but probably as well, so soonest in three weeks I guess) 

> What do you mean with "Update code for msvcrt bundling in prepare_portable"? Is there something still to do?

Python requires the Visual C libraries, these have to either be installed on the system, or bundled with the portable. Since it's not guaranteed that the required version is already installed we bundled them with the portable. Python 3 used a newer version of Visual Studio, so I have to update the bundling code to pull the correct versions from the build system into the portable.

**Comment by emanuelschuetze** [comment]
Ok. Please ping me here if you have fixed the last issues.

**Comment by ostcar** [comment]
@andkit Do you know what the licence of the Visual C libraries are?

**Comment by emanuelschuetze** [comment]
[openslides-potable](https://github.com/OpenSlides/openslides-portable) and [openslides-gui](https://github.com/OpenSlides/openslides-gui) are new repos which handle the portable and gui version of OpenSlides. Works for 2.0b1 with Python 3.3+. So all done for  me.
