### ISSUE TITLE
Administrator can be deleted

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1452]
If you logged in as admin you can remove the admin user in the users list. Please prevent this. User should not be able to remove super user (admin) and himself.

**Comment by normanjaeckel** [comment]
This was a feature of or (Django) views called lockout protection. A user with permission to manage users was not able to delete or disabled himself or delete the last group with the permission he is in and so on. So we have to decide whether to do this check in he REST api on the server or client side.

**Comment by emanuelschuetze** [comment]
I want to see it in the REST api (that other clients, like mobile-app, does not run into the same problem).

**Comment by DerPate** [comment]
i agree with @emanuelschuetze  the best verification of permissions is always done on the server side where no hack can be easily can be applied

**Comment by normanjaeckel** [comment]
See #1457.

**Comment by normanjaeckel** [comment]
To implement lockout protection there are several cases. Who wants to do some of them?
  - [ ] Someone deactivates himself.
  - [ ] Someone deletes himself.
  - [ ] Admin deletes a group so that he has not enough manage perms any more.
  - [ ] Admin removes himself from a group so that he has not enough manage perms any more.
  - [ ] Admin changes perms of a group so that he has not enough manage perms any more.
  - [ ] Anything else?

**Comment by normanjaeckel** [comment]
There is some old code here: https://github.com/OpenSlides/OpenSlides/blob/c8dfb9437b08d0350073a3d7e8d065e20de868e2/openslides/users/api.py

**Comment by normanjaeckel** [comment]
Two cases fixed. The rest is still open. Who wants to do this?

**Comment by matakuka** [comment]
I tested this again for admin, and I still can lock myself out in the case of:
- [ ] Admin deletes a group so that he has not enough manage perms any more.
- [ ] Admin removes himself from a group so that he has not enough manage perms any more.

Trying to delete admin did not work, but no error message was shown.

**Comment by FinnStutzenstein** [comment]
I can do the group delete protection, because this could be easily implemented in the permission matrix.
The removal from a group has to be placed in a more generic spot, because this could be done from diffrerbt places (list view, edit form, ...). IMHO the best place for this is on server side on the users save method.

**Comment by FinnStutzenstein** [comment]
I (admin) could not delete the group staff, if this is the only admin group. See the hover menu in screenshot. @matakuka could you verify this? (it is just a client site protection, a delete request could manually be send...)

![group_delete](https://cloud.githubusercontent.com/assets/8439581/21769826/e053b2f2-d680-11e6-8e18-3898b6454869.jpg)

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Whats about to implement the ["danger-check"](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/users/static/js/users/site.js#L1228) also on server side? Now someone could create a request and lock himself out, because the server doesn't check this.

**Comment by matakuka** [comment]
@FinnStutzenstein You're right, group 'staff' cannot be deleted. It was a 'false alarm' on my side.

**Comment by normanjaeckel** [comment]
@FinnStutzenstein No problem. Of course we should add the lockout protection on server side. Please see my comments in this thread (comment from 14th Feb. 2015 and later).

**Comment by ostcar** [comment]
I think this can be fixed very easily on the current master.

We have a super_admin_group now. So when a user in this group can not remove himself from this group and can not delete himselm, then there is always at least one admin left. So there is no need to check specific permissions on the server anymore.

**Comment by tsiegleauq** [comment]
Seems not relevant for 3.0
set on TODO for now
