### ISSUE TITLE
Provide django-url-names in angular

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1453]
Please check if it possible to provide the django-url-names (e.g. "user_print") for using with ui-sref in angular templates.

**Comment by normanjaeckel** [comment]
Although we can merge #1466 so that client has access to some urls I don't like this solution very much. I think we should use the API only for data an independent client might use. So the question is which URLs does an independent client need. If we want to provide PDF not only for our client but even for e. g. Android Apps we should implement the PDF as public API like the API we have, not inside a huge collection of some URLs that might be useful.

**Comment by ostcar** [comment]
What do you mean with "data an independent client might use"? If a smatphone app wants to access the pdf, it can also use this url.

**Comment by ostcar** [comment]
@normanjaeckel Please explain what you do not like at the current solution or close this issue

**Comment by emanuelschuetze** [comment]
@normanjaeckel ping

**Comment by normanjaeckel** [comment]
As mentioned above I do not like the current solution. At the moment we only use it for PDFs so if we later have jsPDF we can remove this view and the corresponding JS code.

**Comment by ostcar** [comment]
So we can close this issue, like #866 (you closed #866, but jsPDF is not implemented yet.)

**Comment by normanjaeckel** [comment]
This issue should be open to remember us to remove some code after implementation of jsPDF. (#866 has to be closed because we do not want to use Django path finders any more when jsPDF is implemented. If someone wants to implement the path finders only for the time until we have jsPDF he can reopen the issue and assign himself.)

**Comment by normanjaeckel** [comment]
PDF is gone on server side. Now we can remove this hook I think.
