### ISSUE TITLE
Decorate IndexView in urls.py or dispatch().

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1476]

**Comment by ostcar** [comment]
Please do not do in in the urls.py This should be a feature of the View.

**Comment by ostcar** [comment]
Suggestion: You create a CSRFMixin in utils.views that ensures, that the cookie is set. This mixin gets included in the IndexView.

Before the client can send a post, put or delete request, the cookie has to be set. Django only sets the cookie on form views (thats, what the csrf template tag does). Maybe there are other views instead of the IndexView that could need the CSRFMixin. But I do not see another at the moment.
