### ISSUE TITLE
/agenda/print does not work for anonymous user 

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1518]
Try to get agenda PDF via /agenda/print:
* works for logged in user
* does NOT work for anonymous user (redirects to `/users/?next=%2Fagenda%2Fprint%2F` and does not open PDF)

**Comment by ostcar** [comment]
This is expected behaviour :)

You have to activate the anonymous user. If the anonymous user is not active, you are redirected to the login page, which is the user-list-view (at this development state).

The question is, why can an anonymous user see the agenda, if config['system_enable_anonymous'] == False. But this is an other (new) issue
