### ISSUE TITLE
Overlapping projector slides

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1632]
There seems to be something wrong if you activate e.g. the agenda slide and some item detail slides or custom slides. The 'prune_elements' post seems work correctly but the old slide on the projector will not clear. After reload the projector the new slide was shown correctly (without any old slid in background).
So the client-side autoupdate process for slides seems to be broken.

**Comment by emanuelschuetze** [comment]
@ostcar This bug is important for testing. Currently all projector activate buttons does not work correctly... Would be great if you can fix this asap. Thx.

**Comment by normanjaeckel** [comment]
I think the problem is [here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/static/js/core/core.js#L70). We use the default option `merge`, see [js-data docs DS#inject Argument options.onConflict](http://www.js-data.io/docs/dsinject). For the (new) projector (with an object instead of an array) we should  use `replace` but I do not know what is the correct option for all other cases.

**Comment by ostcar** [comment]
I created a pullrequest that fixes this bug. I only changed the onConflict option for projector elements.
