### ISSUE TITLE
Agenda content object requirements

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1692]
Some change requests for related agenda item information provided by rest api (if possible):
* I need the content object real name in singular (e.g. "motion", "election", "agenda item") to show it in delete confirm message ("Do you really want to delete the Motion/Election/agenda item?"). I want to provide a delete link in agenda for the related items.
* `item.content_object.collection` should get a string with "." instead of "/" separator; e.g. "motions.motion" instead of "motions/motion"
* string of (JS-Data) Object name, e.g. "Agenda", "Motion", "Assignment". I want to use it for auto delete command `$ObjectName.destroy(item.content_object.id)`

**Comment by normanjaeckel** [comment]
I added a new field element `display_name`. See #1695.

Why do you want a string with `.` instead of `/`? We defined the collection name used for autoupdate stuff with `/`.

The server does not know the JSData string (i. e. Angular factory service name). The mapping between collection names and these string should be done in the client. -> @ostcar

**Comment by emanuelschuetze** [comment]
> Why do you want a string with . instead of /? We defined the collection name used for autoupdate 
> stuff with /.

I need it for ui-sref links, e.g. `motions.motion.detail`:
https://github.com/OpenSlides/OpenSlides/pull/1698/files#diff-3f7cf361bcdcee23fe42ded55a85d33bR119
But I can use the replace command if other code needs the `/` separator.

**Comment by emanuelschuetze** [comment]
We can close this. I don't need any more special content object updates...
