### ISSUE TITLE
i want to translate to spanish

### ISSUE THREAD

**Issue by johnfelipe** [OpenSlides/OpenSlides#1880]
Hi please accept my join to https://www.transifex.com/openslides/openslides/language/es/

**Comment by emanuelschuetze** [comment]
@ostcar Please accept @johnfelipe in transifex as translator. With my user account I have no manage permissions for OpenSlides organization (don't know why...)

@johnfelipe Thanks for your offer to translate into Spanish! Maybe you can finish your translation (of OpenSlides 2.x resource files) until next Monday. Because we want to release 2.0b2 next week. Then I would add Spanish to this release!

**Comment by johnfelipe** [comment]
@emanuelschuetze then accept me in transifex

**Comment by ostcar** [comment]
@emanuelschuetze I gave you admin permissions on transifex

**Comment by emanuelschuetze** [comment]
@johnfelipe You are now 'coordinator' of the Spanish translation team for OpenSlides! Good luck! :)

All done here.

**Comment by johnfelipe** [comment]
OpenSlides 2.x Django (django.po) is ready

**Comment by emanuelschuetze** [comment]
Great! Thanks! But more important for user interface is "OpenSlides 2.x JavaScript (template-en.pot)". So hope you can finish it today. We'll release 2.0b2 today (this evening).

**Comment by johnfelipe** [comment]
i need 30 min more for complete that
Do u have a full demo instance for that realese, may be share full demo user only for tryout
Please answer me this https://github.com/OpenSlides/OpenSlides/issues/1900

**Comment by emanuelschuetze** [comment]
Our online demo is currently on last stable (1.7). But you can install the new beta release locally.
I'll answer #1900  after release (maybe tomorrow)-

**Comment by johnfelipe** [comment]
@emanuelschuetze **Done both**, do u can share me may be video demostration or screenshot before install it
