### ISSUE TITLE
Request of features

### ISSUE THREAD

**Issue by johnfelipe** [OpenSlides/OpenSlides#1900]
Hi, please tell me what feature is done:

"The system must be configured to support events Plenary .
• The President of the H. Council or operator may install the Plenary session.
• The President of the Council H. puts the above consideration and voting records .
• The President of the H. Council voted to the consideration or the agenda .
• The system should allow public to develop and roll-call votes ,
        by group or secret and define the same time .
• The system should allow before a vote to enable voting module ,
        allowing the YES or NO option , once the vote, the system must shed
        Real-time results for each of the teams H. Aldermen , Board
        and results screens installed in the Council Chambers .
• It should generate a PDF and printed the results of attendance and voting report.
• The results of voting and attendance should be displayed in real time on screen
        enclosure and screens H. Councillors.
• Having an internal chat for all councilors to communicate without interrrumpir the session
• Having a way to upload documents to be observed each session of the council
• Only the President will have a way to have an editable timer , ie could say that
Councilman has 15/30 minutes available for speaking , the timer should produce an audible alert
3 minutes before the term is up and you can put 5/10 minutes from replica "

**Comment by normanjaeckel** [comment]
Some things of the list are already implemented or there may be an accaptable workaround. Others are missing. And some of the features I do not understand. So maybe you try to use OpenSlides and tell us which features your are missing.

Example:
* In comming version 2.0 we have a multiple countdowns for speakers but there is no audible alert.
* We have document upload and am small chat (only one big chat room for the board members e. g.).
* We have PDF reports but I am not sure if they are sufficiant for you.
* We don't have live voting in the core. There is a plugin for this. -> @emanuelschuetze 
* ...

**Comment by johnfelipe** [comment]
@emanuelschuetze please tell me you about this request

**Comment by johnfelipe** [comment]
@emanuelschuetze r u there?

**Comment by emanuelschuetze** [comment]
Some general answers to your requirements if OpenSlides supports it (yes) or not (no).
(If you need special support for a customer - which looks a bit like this - please contact me via email so that we don't have to discuss it in public - see http://openslides.org/en/contact/)

> The system must be configured to support events Plenary .

yes (this requirement is really abstract...)

> The President of the H. Council or operator may install the Plenary session.

yes

> The President of the Council H. puts the above consideration and voting records .

I think yes (don't know what you exactly mean). A staff member has to enter the votings. Or you install a electronic voting plugin for OpenSlides.

> The President of the H. Council voted to the consideration or the agenda .

I think yes (don't know what you exactly mean).

> The system should allow public to develop and roll-call votes ,
> by group or secret and define the same time .

A staff member can input and edit poll results of motions and assignments.

> The system should allow before a vote to enable voting module ,
> allowing the YES or NO option , once the vote, the system must shed
> Real-time results for each of the teams H. Aldermen , Board
> and results screens installed in the Council Chambers .

You can use the VoteCollector plugin for OpenSlides which provides electronic votings (currently for motions only) with real time "live" results on projector and with or without visualized in a seating plan.

> It should generate a PDF and printed the results of attendance and voting report.

yes.

> The results of voting and attendance should be displayed in real time on screen
> enclosure and screens H. Councillors.

yes

> Having an internal chat for all councilors to communicate without interrrumpir the session

yes

> Having a way to upload documents to be observed each session of the council

yes

> Only the President will have a way to have an editable timer , ie could say that
> Councilman has 15/30 minutes available for speaking 

yes

>  the timer should produce an audible alert 3 minutes before the term is up

No, OpenSlides does not support audible alerts - but you can do it with visual alerts (e.g. yellow if <3min, red if <1min)

Hope my comments helps. I recommended you to try the [OpenSlides online demo](http://openslides.org/en/demo/) and read our [full feature list of 1.7](http://openslides.org/en/about/features/). Both, demo and feature list, are still for our last stable OpenSlides 1.7 release. We currently working on 2.0 which can be tested by current 2.0-beta release (see download page).

**Comment by normanjaeckel** [comment]
For specific feature requests please use different issues.
