### ISSUE TITLE
Catch 404 errors if user has no required see permissions

### ISSUE THREAD

**Issue by PaulchenP86** [OpenSlides/OpenSlides#2028]
2.0 b5-develop: Gave all permissions for motions to "Delegates"-group, but if you log in as delegate, you can't click at a motion to see more details (text etc.).

**Comment by emanuelschuetze** [comment]
Looks like the delegate user has no 'see_see_hidden_items' permission. Then you get a 404 error, see https://github.com/OpenSlides/OpenSlides/pull/2030#issuecomment-192706200

**Comment by PaulchenP86** [comment]
Not really sure that I give the correct permission...

[I 160306 18:57:31 wsgi:355] 200 GET /rest/motions/motion/12/ (127.0.0.1) 48.40ms
[W 160306 18:57:31 wsgi:355] 403 GET /rest/mediafiles/mediafile/ (127.0.0.1) 21.45ms

![error](https://cloud.githubusercontent.com/assets/17482167/13555926/a3b81a50-e3cd-11e5-9b6c-75710af285d3.png)

**Comment by emanuelschuetze** [comment]
I can reproduce it now:
If a user has no permission to see mediafiles, hidden agenda items OR users the loading of the motion detail view failed with a 404 error (see [resolve object of motions.motion.deatail](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/site.js#L58)). That's an important (general) issue for 2.0 - because defining reduced see permissions for users caused in these 404 errors...

@ostcar Is there a possibility to catch these 404 errors? Checking if operator has required permissions in resolve part looks a bit to much... and does not work for me)

**Comment by ostcar** [comment]
It seems, that angular ui-router has a problem, if a promise in the resolve part returns a 403.

One solution would be, that you do not load the data in resolve, but in the directive. Another solution would be, that you write your own promise, that does not return 403 but an empty list.

This seems to be another solution, but I could not understand it: https://stackoverflow.com/questions/23877304/angularjs-handle-rejected-response-with-ui-router
