### ISSUE TITLE
Create new motion gets JS error "this.getVersion(...) is undefined"

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2048]
To reproduce:
Create new motion (enter title only). Save. JS console shows error in motion getTitle method. This line in core/base.js is also reference in following error: `DS.inject(data.collection, data.data);`

The error is also shown on all other clients after auto update.
@ostcar Any idea?

```
Error: this.getVersion(...) is undefined
.methods.getTitle@http://localhost:8000/static/js/motions/base.js:138:28
anonymous/fn@http://localhost:8000/static/js/openslides-libs.js line 8 > Function:2:244
o/<@http://localhost:8000/static/js/openslides-libs.js:7:6561
bn/this.$get</p.prototype.$digest@http://localhost:8000/static/js/openslides-libs.js:7:15082
bn/this.$get</p.prototype.$apply@http://localhost:8000/static/js/openslides-libs.js:7:16731
e/p/u[e]@http://localhost:8000/static/js/openslides-libs.js:66:5311
@http://localhost:8000/static/js/core/base.js:185:17
newConnect/socket.onmessage/<@http://localhost:8000/static/js/core/base.js:72:21
rt@http://localhost:8000/static/js/openslides-libs.js:1:3732
An/<@http://localhost:8000/static/js/openslides-libs.js:1:14598
newConnect/socket.onmessage@http://localhost:8000/static/js/core/base.js:71:17
SockJS</r.prototype.dispatchEvent@http://localhost:8000/static/js/openslides-libs.js:21:12911
SockJS</S.prototype._dispatchMessage@http://localhost:8000/static/js/openslides-libs.js:21:26002
SockJS</S.prototype._didMessage@http://localhost:8000/static/js/openslides-libs.js:21:26892
SockJS</S.websocket/i.ws.onmessage@http://localhost:8000/static/js/openslides-libs.js:21:28838
```

**Comment by ostcar** [comment]
I found the bug, but I don't know how to fix it.

On the client side a motion is only valid if it has at least one version. Without a version a motion can not have text, title or reason. So when the server sends a motion with ```{version: []}``` then problems like this one happens.

On the server side, a new motion has to be saved before any version can be added. We first have to save the motion and only then can save the versions in a second step. So for a short moment there is a motion without versions on the server. In theory this is no problem, because this could happen in a transaction. But...

When we save the motion to the database, an autoupdate is triggered. So each client gets the motion without the versions (which are not saved at this moment).

This issue is connected to #2007. We need to find a way to only trigger the autoupdate after an transaction. Maybe this django 1.9 feature can help https://docs.djangoproject.com/en/1.9/topics/db/transactions/#django.db.transaction.on_commit @normanjaeckel any idea?
