### ISSUE TITLE
Delegate group permissions are ignored

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2081]
Create new delegate user and login as this user.
-> All delegate specific permissions does not work. E.g. there is no new motion button! (for stuff users it works). 

Group permissions of delegate user in /rest/users/group are ok (e.g. motions.can_support). So it seems to be a client problem with group delegate.

**Comment by emanuelschuetze** [comment]
I found the problem in the rest api:

A staff user get for /rest/users/user/42:
{ .. "groups": [3] }

A delegate user gets for /rest/users/user/42:
{ .. "groups_id": [3] }

 @normanjaeckel Why the rest api send two different names for groups/groups_id?

**Comment by emanuelschuetze** [comment]
@normanjaekel: ping

**Comment by normanjaeckel** [comment]
Hm. The problem is not the delegate but the admin. We need a fix on server and client side:
@emanuelschuetze: Please test the following: Change `PrimaryKeyRelatedField` to `IdPrimaryKeyRelatedField` in users/serializers.py. If you do this, the admin now gets `groups_id` instead of `groups`. Now you have to change the client so that it expects `groups_id` when handling permissions.
