### ISSUE TITLE
best method for run into subdomain

### ISSUE THREAD

**Issue by johnfelipe** [OpenSlides/OpenSlides#2095]
I have nginx, gunicorn, how can i run my instance in subdomain

gestordeplenarias.jhonfelipeurregomejia.com

But is not set it now, pls give me instruction for do it correctly
Tnks

**Comment by normanjaeckel** [comment]
@ostcar does this for our demo. Maybe he can help.

**Comment by ostcar** [comment]
I did it for our demo. Since 2.0 the demo runs on a server from intevation. I think, they use apache, but i am not sure. @emanuelschuetze ?

openslides 2.0 is not a wsgi application and therefore can not be deployed then a normal django project. You need to start openslides on localhost and use nginx as a proxy to connect to it.

Here is the nginx config I used for 1.7. But it should also work for 2.0
```
server {
    server_name en.demo.openslides.org;
    include include/plain;
    include include/openslides-log;

    location /static/ {
       alias /srv/sftp/openslides/demo-en/static/;
    }

    location /media/ {
        alias /srv/sftp/openslides/demo-en/media/;
    }

    location / {
        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_pass http://localhost:8102;
    }
}
```

**Comment by emanuelschuetze** [comment]
Right, we use the current 2.0 demo with apache.

**Comment by johnfelipe** [comment]
its possible do ti with nginx?

**Comment by ostcar** [comment]
I tested it in a virtualbox and it runs without a problem. I used the config shown above.

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~$ cd /etc/nginx/
	felipe@felipeurrego:/etc/nginx$ sudo cp sites-available/default sites-availableopenslides
	[sudo] password for felipe:
	felipe@felipeurrego:/etc/nginx$ sudo ln -s /etc/nginx/sites-available/openslide sites-enabled/openslides
	felipe@felipeurrego:/etc/nginx$ sudo nano sites-available/openslides
	felipe@felipeurrego:/etc/nginx$ sudo service nginx restart
	 * Restarting nginx nginx                                                [fail]

and

	server {
		server_name gestordeplenarias.jhonfelipeurregomejia.com;
		include include/plain;
		include include/openslides-log;

		location /static/ {
		   alias /home/felipe/OpenSlides/openslides/static/;
		}

		location /media/ {
			alias /home/felipe/OpenSlides/openslides/media/;
		}

		location / {
			proxy_pass_header Server;
			proxy_set_header Host $http_host;
			proxy_redirect off;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Scheme $scheme;
			proxy_pass http://localhost:8102;
		}
	}

Why fails?

**Comment by ostcar** [comment]
You probably have to read the nginx documentation if you want to use this software.

To help you configure it, I need more informations. In which file did you copy to content you pasted above? If you saved it into /etc/nginx/sites-available/openslide then why did you copy the file from /etc/nginx/sites-available/default?

Do you have a file /etc/nginx/include/plain and /etc/nginx/include/openslides-log? If not, you can not include them. The content of /etc/nginx/include/plan at my server is
```
listen 0.0.0.0:80;
listen [::]:80;
```
but you really have to read the documentation, because you can not use one snipped of configuration of my server, use it at your server and expect it to work.

If your nginx configuration is correct, then you have also to start openslides. You can do it manually in a screen session or use an init-script.

If you need more help, then I need a proper error message. I don't know which distribution you use. If it is ubuntu 16.04, then you can type ```systemctl status nginx``` to get a better error message. Or type ```nginx -t``` to check nginx for errors.

**Comment by ostcar** [comment]
Maybe this gist can help. You have to read in the ansible-documentation how to run a playbook. If you can to this, then the gist installs openslides on ubuntu 16.04

https://gist.github.com/ostcar/05140c0d90bf787bfe7814194b609f09

**Comment by johnfelipe** [comment]
Please view this
https://gist.github.com/ostcar/05140c0d90bf787bfe7814194b609f09#gistcomment-1787089

**Comment by johnfelipe** [comment]
i do this:

	cd OpenSlides
	source .virtualenv/bin/activate
	mkdir /home/felipe/OpenSlides/personal_data/var/static
	python3 manage.py collectstatic --settings settings --noinput
	mkdir /home/felipe/OpenSlides/personal_data/var/media
	chmod 775 /home/felipe/OpenSlides/personal_data/var/media
in nginx this
	###
	server {
		listen 8001;
		listen [::]:8001;
		server_name 127.0.0.1 gestordeplenarias.jhonfelipeurregomejia.com;


		location /static/ {
		   alias /home/felipe/OpenSlides/collected-site-static/;
		}

		location /media/ {
			alias /home/felipe/OpenSlides/personal_data/var/media/;
		}

		location / {
			proxy_pass_header Server;
			proxy_set_header Host $http_host;
			proxy_redirect off;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Scheme $scheme;
			proxy_pass http://localhost:8001;
		}
	}

	###

**Comment by ostcar** [comment]
Ubuntu 14.04 runs with upstart and not with systemd. So you have to write a config file for upstart. I never did this and can not help you with that. Before Ubuntu 16.04 I used a screen session in which I started openslides.

**Comment by johnfelipe** [comment]
pls link me manual for that

**Comment by ostcar** [comment]
https://www.gnu.org/software/screen/manual/screen.html

screen is a "windowmanager" for the terminal. So you can access your server with ssh. Start "screen". Then activate you virtualenv inside the screen and start openslides. Then detach you screen session by closing your terminal or by pressing "strg + a" and then "d"

**Comment by johnfelipe** [comment]
i have already there, but i need like subdomain and if reboot ubuntu 14 star automatically openslides
do u get me?

**Comment by ostcar** [comment]
The problem with the subdomain is solvable. All you have to do is fix your nginx config. Nginx has to listen on port 80 and connect to the openslides instance that run inside the screen session on port 8001. Your current nginx config listens on port 8001 (which is wrong when openslides also listens on port 8001).

I can not help you with the autostart problem. Please use ubuntu 16.04 or read the upstart manual.

**Comment by johnfelipe** [comment]
cd OpenSlides
	screen -S OPENSLIDE
	source .virtualenv/bin/activate
	python manage.py runserver 0.0.0.0:8001

is working ok

But how put that automatically every time my server restart?

**Comment by ostcar** [comment]
As I sad before: I can not help you with that. Please use a distribution that uses systemd or read the upstart documentation. This is not openslides related, so I close this issue here
