### ISSUE TITLE
Use textarea field for config login info text

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2099]
This is that people may add linebreaks to the text.

**Comment by donovaly** [comment]
My bug report is not about line breaks but that longer text is too long to view it completely in the current field. So the field should be a text field instead of a line input.

**Comment by donovaly** [comment]
Peter, you got me wrong. This bug is about that the text in the green area at the login screen:
![welcome-text-field-bug-1](https://cloud.githubusercontent.com/assets/1828501/15269188/16864ed4-19f8-11e6-914e-e06ea8a2d8b7.jpg)
has to be entered in the settings in a line edit:
![welcome-text-field-bug-2](https://cloud.githubusercontent.com/assets/1828501/15269193/29b2e120-19f8-11e6-95b6-be1c8e7dd580.jpg)
but instead of a line edit the field should be a text field like it is e.g. for the impress:
![welcome-text-field-bug-3](https://cloud.githubusercontent.com/assets/1828501/15269197/3cba0f46-19f8-11e6-94a8-326b10e3a62c.jpg)

**Comment by emanuelschuetze** [comment]
As discussed with @normanjaeckel and @matakuka : 
We don't like it to provide a textarea for the login info text config option. Currently we use always input, lists, checkboxes or editor fields - no texarea. To reduce the complexebility of config page we want to keep it just in simple input field if possible. For login info text the text length of this config value should be limited (to protect users for very long 'greeting' texts).

So let us keep the current input field.
Workaround for adding linebreaks: use`<br>`.

Closed.
