### ISSUE TITLE
2 default participant groups not selectable

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2122]
- go to the participants list
- edit a user and try to set the group Guests and/or Registered users

result: these 2 groups are not listed in the edit participant dialog

At least setting a user as guest makes sense and should therefore be possible.

**Comment by normanjaeckel** [comment]
We have two system groups: One for anonymous guests and one for registered users. It is not possible to set a user to one of this groups because every registered user gains all permissions from the group registered while every anonymous user (without login) gains the permissions of the guests group. You can use these groups only to control permissions of these types of "users". This have to be explained in the manual.

**Comment by donovaly** [comment]
> This have to be explained in the manual.

Done now.

> while every anonymous user (without login)

How does this work? I played around but cannot find a way to use OS without logging in.

**Comment by donovaly** [comment]
> How does this work?

OK, I found now the corresponding option and documented it.
