### ISSUE TITLE
regression: minimal numer of requires supporters for motions is not respected

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2162]
- in the motion setting use e.g. "2" as required minimal number of supporters for new motions
- now create a new motion but without any supporters

result: the admins can change the status of the motion despite to accepted it has no supporters whiel 2 supporters are required according to the settings.

This bugs looks very much to be a regression.

**Comment by normanjaeckel** [comment]
This is not a bug. The admin is allowed to change the status even if there are not enough supporters because he may check support also outside OpenSlides. We do not want to block him to handle urgent motions. The setting of the required supporters is only to display a message if there are already enough or not or to disable supporting system.

**Comment by donovaly** [comment]
OK: I'll document this.
