### ISSUE TITLE
staff users can remove delegates from motion support list

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2171]
- a delegate logged in and supported a motion
- now the staff users/admin can remove this user from the support list.

This is a problem because at least in political parties members fear misuse all the time and in this case the admin could remove a person from the supporter's list against his will.

**Comment by normanjaeckel** [comment]
This was a design decision: The admin/stuff should be able to support semi paperless assemblies. If someone comes to him (shows his ID) and says that he do not want to be a supporter of a motion any more, the admin should be able to remove him. (The admin is also able to change and reset the password of this user, log in using his credentials and the support oder unsupport motions.) The admin is even able to hack the database and change data to whatever he likes for OpenSlides does not use crypto stuff here.

If the members of an assembly do not trust his admin they should not use his software for some aspects of their work (e. g. elections).

**Comment by donovaly** [comment]
> If the members of an assembly do not trust his admin

Of course many people don't trust "new" things. I cannot accept that this bug is closed without any discussion.
I cannot follow you argumentation: The user already logged in and presses the support button, so he can log in again and unsupport. So there is no need for the admin to do this. If a user refuse to log in again and to unsupport it is his decision.

Also for a later feature to support elections the admin must not be able to change election results. This is a very important issue to get acceptance for a software like OpenSlides. If you deny to rethink about the design for OpenSlides I fear it cannot be sued as a tool that supports also elections.

Please reopen the bug and discuss a close first (maybe on a phone call conference or by mail).

**Comment by normanjaeckel** [comment]
I can imaging many situations where someone want to support or unsupport a motion but is not able to log in (at the moment or at all):
* May be the admin uses OpenSlides in presentation mode so he does not share user credentials and does not want to give participants network access. He just wants to control what is shown on the projector.
* May be the user has not computer. He just asks the admin for service. (And it may be a decision of every assembly whether to offer such a service or to offer a public computer terminal.)
* May be the user misuses his accounts and has to be blocked. Nevertheless his request to support or unsupport the motion is valid according to the legal system of the assembly.
* ...

All in all users of OpenSlides have to have the choice how to use it. If users request a more secure version we need personal software or even hardware certificates, signatures, card readers, an independent CA and thelike for every action a participant may do. This is because the admin is able to change every (unsigned) value of the underlying database all the time. So we should not discuss about how to restrict the UI for admin users.

**Comment by normanjaeckel** [comment]
If we later implement personal elections using the credentials OpenSlides currently provides (no extra crypto stuff) then this is the same. The election should no be considered valid because OpenSlides has not button for the admin to change/remove votes but because in the end everybody is able to check if his vote was counted correctly. (OpenSlides should provide a printable (ordered) named list of all votes.)

**Comment by donovaly** [comment]
> May be the admin uses OpenSlides in presentation mode so he does not share user credentials and does not want to give participants network access. He just wants to control what is shown on the projector.

But this is not the bug. The bug is when the user already logged in and added himself to the supporter list. if OpenSlides is not used that way users can log in he would not be able to add himself to the list before.

> May be the user has not computer.

But again, the bug is if he already logged in before. If he lost he computer meanwhile, he must login from another PC. That should not be a hard task.

> May be the user misuses his accounts and has to be blocked.

This is not allowed. A member of e.g. a party has certain rights that cannot be removed. If anybody has the right to participate via OpenSlides it is not allowed to hinder him. if he pulls out 200 motions at once it is his right to do  and this happens in practice. People know how to ignore this or to put such motions to the very end of the list so that there is always "unfortunately" time to speak about this.

**Comment by emanuelschuetze** [comment]
@donovaly Please accept that we have to prioritize all reported OpenSlides issues. And this issues has a very low priority for us. We (the core developers) have to allot our (reduced) time slots to bring OpenSlides to the front by implementing the most useful things for all organisations and their assemblies.

This issue is not a valid bug for us because our basic assumption is that all admin users of OpenSlides are trusted persons in the assembly. If it not valid for your event you have to think about organisational actions by using OpenSlides (e.g. that users have to support motions only by signing on motion paper). We cannot protect OpenSlides against malintent administrators! This is a requirement (as in every software).

So please let us concentrate on issues where we are agree with the suggested improvements and which are helpful for all the other organisations using OpenSlides. (Please call me personally if you have still some questions to my decision.)
