### ISSUE TITLE
Add new config option for 100 % base of voting results (yes+no without abstain)

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2182]
Add to the config field "The 100 % base of a voting result consists of" (in section motions and elections) a new select option:
"Only YES and NO values"

Add a check for this new config option in [motions/base.js](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/base.js#L86) and [assignments/base.js#L38](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/assignments/static/js/assignments/base.js#L38) and [assignments/base.js#L107](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/assignments/static/js/assignments/base.js#L107).

**Comment by matakuka** [comment]
For motions there is currently no way to alter the settings of "motions_poll_100_percent_base" -- should it mirror the settings of the election method (with invalid/without invalid/ without abstains) ?

**Comment by normanjaeckel** [comment]
What do you mean by
> currently no way to alter the settings of "motions_poll_100_percent_base" 

? Is this a bug? Maybe you have to checkout the current master because we fixed a bug in the config recently.

**Comment by matakuka** [comment]
my bad, I was looking at the wrong line. Works fine

**Comment by normanjaeckel** [comment]
We should discuss the goal of this issue in the different use cases:

# Motions

We only support one voting method: You can fill out six fields per motion poll: yes, no, abstain, votes valid, votes invalid and vots casts.

This issue is about the new possibility that the percent values should base on the sum of yes and no votes instead of the field valid votes or votes cast. No problem here.

# Assignments

At the moment we support three voting methods:

## Config value `votes`

In this voting method you can fill out for one poll one field per candidate and three global fields (votes valid, votes invalid and vots casts).

Here is the question about what this issue is. I do not know and I can not imagine at the moment.

## Config value `yesnoabstain`

In this voting method you can fill out for one poll three fields per candidate (yes/no/abstaion) and three global fields (votes valid, votes invalid and vots casts).

Here is the question about what this issue is. Should the percent base the sum of all yes and no fields of all candidates?

## Config value `yesno`

In this voting method you can fill out for one poll three fields per candidate (yes/no/abstaion) and three global fields (votes valid, votes invalid and vots casts).

Here is the question about what this issue is. Should the percent base the sum of all yes and no fields of all candidates? Is there any difference to the behavior of case 2?

## Config value `auto`

In this case OpenSlides just chooses one of the methods above so we do not have to care about this case here.


# Conclusion

The implementation in #2192 changes the behavior  of some of this cases in a way that does not fit with structure of our voting system. First we should look at the different voting methods and what we would expect from a change here.

**Comment by matakuka** [comment]
The new config value is valid only for two cases: Motions and assignments/yesnoabstain. As in the other cases no abstain appears, it behaves as *yes/no (including abstains)*  does.
(note: In the voting methond  *yesno* you can not abstain.)

- John Doe has 40 Y / 30 N / 30 A votes, 100 voters
 - "40% Yes" respects all voters, and shows that John has convinced less than half of the voters.
 - "57% Yes" shows that John has far more followers than enemies, which is a bit clouded by all those who simply don't care about John.

I think both options have their value, and an assembly may chose either method for display results.

The problem I am seeing now, and where it needs discussion, if this option is to be included,  is when there are **multiple candidates with Yes/No/abstains**. There the base of *Yes/no without abstains*  is not calculable on poll basis, as there will be different amounts of abstains for each candidate.
I think we need some input from @emanuelschuetze  as well, about what was the original intention of this issue regarding the different voting methods.

**Comment by emanuelschuetze** [comment]
Reopened: #2319 is still open

**Comment by emanuelschuetze** [comment]
Already fixed, see #2319 .
