### ISSUE TITLE
Delete multiple speakers – How to handle error

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2237]
If you want to delete multiple speakers, you can send an array with ids. How to handle an error here  (e. g. an invalid speaker id)?

a) Delete nobody? Then we have to add `with transaction.atomic():` to the viewset method.
b) Delete all valid speakers? Then we have to add `break` to the viewset method.
c) Something else ...?

**Comment by matakuka** [comment]
**case 1**: a request that is malformed and may have had a destination elsewhere, but contains entries that could read as valid speaker_ids. In this case we should verify if the list really (only) contains speaker_ids that exist in the database, and not rely on the client committing good lists. At the moment I don't see such a malformed request arriving, but I'll think about it this weekend.

**case 2**: A privileged user could send `DELETE {speaker: [long list of random numbers]}`, making the system run slow until every number is checked. --> TODO: checking if there are still speaker_ids on the list of speakers? Also, stopping the checks if there has been a certain amount of errors?

**case 3 (most common)**: a request that contains speakers to be removed, but also contains speakers that are not on the list (e.g. because they were already removed by another client), or are not in the database anymore (user was deleted) --> In this case you would want to delete those that are still in the list of speakers.

So my first thought is this: Delete all valid speakers, stop running the query if there's no speakers left, and aborting if the list contains numbers that are not/(have never been?) in the database.

**Comment by normanjaeckel** [comment]
Hm. If we abort we should tell the client which speakers are deleted and which not. With one invalid id in the middle of the array the valid speakers at the end of the array are not deleted. So I prefer to continue parsing the rest of the array to delete all valid speakers. Of course a privileged user may run a DoS attack here (case 2) but I don't think this is a real danger.

**Comment by matakuka** [comment]
The behaviour now is more or less as wanted: loop through the array, and try a deletion for each speaker. Upon successful delete, a success message is created, for every fail a failure message. A failure occurs whether the user is  not on the list or the user does not exist. 

**As the loop happens fast, no (or only the last) message will be displayed.** 

We could:
- collect these messages and display a (potentially long) summary of messages.
- Differentiate between *users not on the list of speakers* and *users not existing*

Possible aggregated messages:
- short: `"10 users were deleted from the list of speakers, 5 requested deletions were unsuccessful"`
- long: `"User1, User3, User 5, User 8 were successfully deleted from the list of speakers, User4, User6, User9 were not deleted from the list of speakers because they have not been on the list, User_id: 999 was not deleted from the list of speaker because the User does not exist"`
- extensible: `"Deletion completed. Some requested users could not be deleted from the list"` - upon click a popup/new window with a table showing successes/failures and (possibly) the reason.

**Comment by emanuelschuetze** [comment]
Still open, as discussed with @normanjaeckel and @matakuka :
* delete all speakers, ignore invalid speakers
* send general success message with the number of deleted speakers
