### ISSUE TITLE
The "back" button in /core/tags doesn't work after creating a new tag

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2267]
When creating a new tag, the "back" button doesn't navigate to the origin, where one has clicked on "Tags". Instead, one is redirected to the new tag page, because a `history.back()` is used. This is very irritating.

**Comment by emanuelschuetze** [comment]
First, we should discuss it and think from user side.
@matakuka You implement the back button in #2183. What do you mean? Should we remove the button again?

**Comment by matakuka** [comment]
A `history.back()` goes back to the last time the URL changed, which is not always the last time the state changed. For `state` changes, we have no memory yet.

Also, it is not always well defined where "back" is:

Most of the time, a "back" should send us upwards in the hierarchy. The hierarchy is modular, so Tag is top-level, but you may have been on Agenda before. There are also cases where I want to go back to where I came from, which might be `tags <- agenda/item/#  <- motions/motion/detail`, for example, not following a hierarchy at all.

I think the problem in the other issue was that we could not determine where the user came from, and instead of having no button, I inserted a history.back(), which made sense in this case. However, if the user went through state changes, "back" is different.

Possible solution: 
- A "memory" of where the user has been could be implemented as an array, so that each state appends itself, and the "back" button just works backwards through this. An array because we don't want only *one* step back, but several. Maybe limiting it to a certain amount of states.
 - Every state change needs to report to this function (best placed in core?), on every "back" trigger we need to modify this array and go to a state. 
 - *I'm not sure if we don't need to transport objects through state changes, which may be lost in the confusion*.
 - *Some* state changes shouldn't be accessible through "Back", e.g. forms.
 - Some state changes can not be executed if the user's permissions change during the session.
- A "upwards" button which always points to the upper level, if there is one (agenda/item/1 points to agenda). Here several pages must remain without that button, as there is no "up" for e.g. Tags.

**Comment by FinnStutzenstein** [comment]
Or is it somehow possible to save only for the tag page, where the user come from in one variable. So by clicking back, the user is sent to where he comes from. It should be a must, when entering the tag page, to give this as an argument, so the tag page always know where to go back. But coming from edit or new, the argument could be `none` so the last state does not get overwritten.
So you don't have to track every site and statechange, but only the important ones, namely where does the user come from, when he enters the tag page.

**Comment by matakuka** [comment]
I think we should tackle this issue globally, not only on the `Tag` page, as there are other pages where the user could arrive from different places.
- e.g. `agenda list` -> `edit election`: After updating the election you are on their `assignments/#` page, which leaves you with an `all elections` button, but you might want  "back" to be the agenda list, which is two or three states ago. `history.back()` should not work on this example, either.

**Comment by normanjaeckel** [comment]
+1 for global solution. But if it is easy and nobody has time to solve this problem globally I could live with a temporary partial solution.

**Comment by emanuelschuetze** [comment]
Suggestion: Show tag form in ng-dialog, then the back button (from tag list view) works as expected.

**Comment by emanuelschuetze** [comment]
Done in #2973
