### ISSUE TITLE
Load all at the beginning

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2295]
At the moment we do not load all data at the beginning of our AngularJS app. But on almost every page we load almost everything in complex resolve-loadRelations constructions. Sometimes we use findAll which might be not correct.

So what about just load everything at the beginning and then remove all resolve and find and findAll code to cleanup a little bit?

**Comment by matakuka** [comment]
The main problem is that the resolved data is not static, and javascript does not know the server data changes without asking. Resolve just asks on page loading/ state changing.

Which is fine the moment you open a state. But I've run into several problems where *new* data since the last resolve were not included, so I had to turn to `getAll` or loading relations midway in the code, because a new item was not in the list.

Loading *all data* at the beginning would not work either, for the same reason. It will just spam the browser cache. New items will ony be included if they are produced in the same DOM (i.e. same window).

**Comment by normanjaeckel** [comment]
I think this is what our autoupdate is about. New items come from websocket and are saved into the DS (jsData). Then the array created with findAll() (either in a resolve or in a controller) will be updated automaticly. Some missunderstanding ...? @ostcar may help.

**Comment by tsiegleauq** [comment]
> It will just spam the browser cache
Yep, it probably will. Depending on how much data has to be loaded from the server, this might cause performance issues.

I honestly think in OpenSlides case Lazy loading is the way to go
https://en.wikipedia.org/wiki/Lazy_loading

**Comment by matakuka** [comment]
My observation on autoupdate is this:
```
resolve all User and Agenda
get one agenda_item from the list
display agenda_item.speakers in template
```
The agenda_item.speakers will be autoupdated and show the users. 
If a new user is created (by a different browser instance with different cache) and added to item.speakers, the new user *does not appear*, but an empty line.

item.speakers will autoupdate and link to a new user.id, but the user(new user.id) does not exist for the browser until the next resolve ==> we have a list of *all* users in the cache, but this list is outdated.

**Comment by matakuka** [comment]
I had some further reading into autoupdate.
The data only gets out of sync if we are not connected to autoupdate of the data. 
This happens if we don't have privileges, and if the connection is lost.

You can get outdated data in your client:

1. If you load the page without resolving
2. If you lose internet connection or websocket connection
3. If you are logged out, you won't receive updates
4. if you log in with more permissions than before, but on the same browser

At these instances you'll need to resolve all data to be able to keep up. Or at least the diff between your browser cache and the server.

Still, I think this can be quite some spam in the browser cache, as you are cloning most of the database. I'm unsure how much this could be, and how much is available.

**Comment by emanuelschuetze** [comment]
see #2854
