### ISSUE TITLE
Add migrations for new permission matrix

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2315]
We need a migration file from v2.0 to v2.1. Therefor we need a concept how to handle old (maybe customized) and new groups.

**Comment by FinnStutzenstein** [comment]
in 2.0 there are these groups:
1: Guests
2: Registered users
3: Delegates
4: Staff
5: Committees
6: Group_1
9: Group_4

Now, Group `Guests` has the same permissions as `Default`, so just change the name.
`Registered Users` has to be deleted. Maybe it is possible to decrement all ids >= 3:
1: Guests --> 1: Default
~~~2: Registered users~~~
3: Delegates --> 2: Delegates
4: Staff --> 3: Staff
5: Committees --> 4: Committees
6: Group_1 --> 5: Group_1
9: Group_4 --> 8: Group_4

now, there are some missing permissions for all groups (excluding `Default`). My suggestion is to add all former permissions of `Registered Users` to all groups with id >= 2. if the admin do not want this, he has to change it by himself, but everybody has at least the basic permissions.

I don't exactly know whether this is possible, but if it is, it could be a good solution.

**Comment by normanjaeckel** [comment]
In 2.0 there was no group Committees.

**Comment by normanjaeckel** [comment]
What about the following:
1. Rename group pk=1 (Anonymous) to `Default`
2. Rename group pk=2 (Registered) to something like `OldRegistered` but do not delete it.
3. Add all users, that are not member of a group to this group.
4. Add all permission of this group (pk=2) to all other groups.

So we have all advantages @FinnStutzenstein described above and also old users without any group may get the permissions they had before (and not some other permissions of the group pk=1).

Still open problem: Please check the `create_or_reset_admin` function. This should readd admins to the group staff.

**Comment by FinnStutzenstein** [comment]
So, the fixed assignment between Delegates -> 2 and Staff -> 3 is not important? If not it is a good solution, because the user can decide, what he want to do with the old group. 
`create_or_reset_admin_user` tries to find the group `staff` with pk=3. This would give problems with the migration, but also if an admin have build their own groups-structure, this may fails. I think, there should be more logic like searching a group with a minimum of permissions and adding the admin to this group, or if there isn't any group like this (maybe deleted, etc.) `create_or_reset_admin_user` should create a group with all needed permissions for the admin.

Another suggestion: In the users import, the associated groups are named by their ids. Whats about giving the groups by their name, so if a group does not exists, it could be created like the categories in the motions import. And If the ids of `staff` and `deligates` are not consistent, this would simplify the whole process.

**Comment by normanjaeckel** [comment]
Done with #2370.
