### ISSUE TITLE
Synchronization problem when deleting a version

### ISSUE THREAD

**Issue by thoessl** [OpenSlides/OpenSlides#2363]
If one browser (tab) is specific version of a motion and another browser (tab) deletes that version, the output in the first browser becomes somewhat useless: while the "Version History" section is updated correctly, the motion text becomes "undefined" and the version number at the top vanishes.
It seems like the motion variable in the first browser is updated through the data synchronization mechanism, but not not the "version" variable. It works in the browser that triggers the deletion, though, as $scope.showVersion(motion.active_version); is called in the callback of the delelete-function.

One more thing, I don't know if it is intentional or not: the "Reason" text always shows the most recent version of the version, not the currently selected version.

**Comment by FinnStutzenstein** [comment]
I looked at this and I would say this is a won't fix. Every autoupdate works fine, also the deletion. But if you look at a specific version and another user deletes it, your client removes the version from the storage and your view becomes broken.

Compare to everything else: If you have a motion open and someone else deletes this motion, your view also becomes corrupted, because the data isn't anymore present.

@emanuelschuetze @normanjaeckel ping
