### ISSUE TITLE
Use password validation?

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2372]
Django 1.9 offers [password validators](https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators). Do we want to use them? They can not be enable by adding the to the settings because we have a special reset password viewpoint.

**Comment by ostcar** [comment]
I don't like password validators at all. I want to be free to use a weak password on an not important website.

**Comment by tsiegleauq** [comment]
That's the responsibility of the users. I would not really like to patronize them. We could, however, make password validation configurable in the client. Not that it would help much, since you can always get around client side validation.

Closing for now, since it wasn't relevant for a couple of years.
