### ISSUE TITLE
ui-tree: can't sort agenda

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2452]
In current master I cannot sort the agenda with the ui-tree. I can drag an item, but the dashed placeholder where I can drop the item does not appear
![imag2815](https://cloud.githubusercontent.com/assets/8439581/18945510/31d56086-862b-11e6-93ab-87091471dd31.jpg)
(sorry for the bad 'screenshot')

I had dropped this item at the shown position and it got inserted at the top.

**Comment by emanuelschuetze** [comment]
Suggestion to optimize performance:
Add a "Save" button above the draggable items. After sorting items use have to click save once. Advantage: There is only one request to server - not one after each drag&drop action.

**Comment by emanuelschuetze** [comment]
As discussed with @normanjaeckel : 
Replace the patch request in [agenda/site.js#L585](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/agenda/static/js/agenda/site.js#L585) by a single post request. Add a new view on server side to save all given items. Send one autoupdate for all changed agenda items. 
Maybe with this optimization we don't need the "save"-button-suggestion because we send only one reqest instead of n requests.

**Comment by emanuelschuetze** [comment]
Fixed with #2925  (more improvements for sort view see #2928)
