### ISSUE TITLE
Extend autoupdate API for non-models.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2468]
It should be possible to use the autoupdate API for fake models. See #2281.

**Comment by ostcar** [comment]
I think this is fixed in the current master.

`inform_changed_elements()` (https://github.com/OpenSlides/OpenSlides/blob/e8a141387b05977a44eb8c60ef95ebff079e6936/openslides/utils/autoupdate.py#L87) accepts a "fake model" if it has the values id, collection_string and full_data.

In `handle_changed_elements()` the fake model can be saved into the cache, if it is registered as `Cachable` (https://github.com/OpenSlides/OpenSlides/blob/e8a141387b05977a44eb8c60ef95ebff079e6936/openslides/utils/cache_providers.py#L476)

So what you have to do to use a fake model is to create it with the methods `get_collection_string()`, `get_elements()` and `restrict_elements()` where the elements are a dict with at least the key `id` which is an int. Then you have to return this fake models with your AppConfig.get_startup_elements().

So I think this was fixed with #3974. If not, please reopen
