### ISSUE TITLE
OS 2.1: missing translation in agenda projection submenu

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2531]
- In OS 2.1 dev create a subentry of an agenda point
- click on the arrow button besides the projection button to show the submenu

result: there are 2 subentries while there should only be one and the second one is in English instead of in German, see the screenshot:

![bugxxx](https://cloud.githubusercontent.com/assets/1828501/19707668/3a71d35c-9b19-11e6-8e92-eb8e3deaba9d.jpg)

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Any idea how we can easily define the translateable string "Default projector" once on client site, so that we can use the already translated string with `{{ projector.name }}` in template? Currently, the projector name string is defined on serverside only, see [here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/migrations/0006_multiprojector.py#L16)

A not so nice/generic solution would be to add the gettext('...') to site.js and use always {{ projector.name | translate }}` in templates. But there a lot of places in templates... Maybe you find a better solution.

**Comment by FinnStutzenstein** [comment]
This is the only solution (except query on projector create the language, but this is not nice). See the groups-name handling. Except Staff, Committee, Registered and Delegates all group names are custom, but always (because of this four groups) we need to set the translate tag. I'll to this.
Could we just add `gettext('Default projector');` [here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/static/js/core/site.js#L1348)?

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze or [here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/static/js/core/projector.js#L266)?
