### ISSUE TITLE
OS 2.1: unexpected screen jumps when marking persons as elected

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2555]
- create a vote with many persons to be elected. Take e.g. 10 persons.
- do the election and now mark a person as elected by clicking into the box in front of its name

result: the person is marked as elected but the screen view jumps to the top of the page. So for every person to be marked one has to scroll a lot. This is annoying if one has e.g. elections for a board of many persons

**Comment by emanuelschuetze** [comment]
Confirmed. Richt, this is very annoying.
@FinnStutzenstein Any idea how to fix it?

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze this has something todo with the ng-repeat (it does create the table new, if the data has changed), so that in a small moment of time the table has no body. Then the whole OS-page shrinks in size, so the browser scrolls up that the end of the page is at the bottom. After that, ng-repeat builds the table, the page gets larger but the browser stays at its scroll position.

You can reproduce this very easy: Inspect the table and search for the <tbody> tag (in Dev-Tools). Then add `display: none;`. The page scrolls up. Then remove the new style, so that the table is displayed, but the browser stays there.

**Comment by emanuelschuetze** [comment]
Debugged together with @FinnStutzenstein:
The screen jumps are not caused by using uib-tab. It is caused by `ng-repeat="poll in assignment.polls" ` of election results. After each assignment autoupdate the ng-repeat-poll container is scrolled. We assume that the ng-repeat container gets a height of 0 if assignment is updated. We have to find a solution for that. Workaround: a min height for the ng-repeat container... Not very nice...

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Can we move this? The ratio between the effort to fix this and the usability benefit is not very high..

**Comment by donovaly** [comment]
Many thanks, confirmed fixed.

**Comment by donovaly** [comment]
Please reopen because this bug is back in OS 2.3b4.

**Comment by emanuelschuetze** [comment]
Sorry, this is a minor issue. Works good enough for 2.2 -> moved to 2.3

**Comment by donovaly** [comment]
> this is a minor issue

Not for me. I took unnecessary long time to mark 15 persons as elected before I could publish the result. In this time the audience had to wait - not a comfortable situation for me as admin. To repeat myself, what admins don't have during an assembly is time.
Moreover, it is a regression, because it was already fixed.

**Comment by jsaalfeld** [comment]
Since the client is completely rewritten for OpenSlides 3.0, this shouldn't be an issue anymore. Please reopen if otherwise.
