### ISSUE TITLE
Motion line numbering pdf layout issue

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2561]
If you print a motion with an ul or ol list, the line numbers are moved behind the bullet points or item numbering - in the same column as line numbers.

**Comment by tsiegleauq** [comment]
Maybe I should elaborate on this issue a little.

This is how the current state for outer-line-numbers looks right now:
![bildschirmfoto von 2016-11-30 11-38-44](https://cloud.githubusercontent.com/assets/10233032/20749339/3bf6cc2e-b6f2-11e6-9398-26cb7e73a4df.png)

This is how it is supposed to look:
![bildschirmfoto von 2016-11-30 11-44-05](https://cloud.githubusercontent.com/assets/10233032/20749372/5f9f0c86-b6f2-11e6-9b4e-e45d80b02161.png)

The main problem with the html to pdf parser is, that the information given my the HTML code do not correlate with the way it is supposed to look.

![bildschirmfoto von 2016-11-30 11-46-10](https://cloud.githubusercontent.com/assets/10233032/20749437/aced308a-b6f2-11e6-8089-5546dbb32a43.png)

As you can see, the current implementation of the line-number-feature nests the information about the numbers in the `<span>` tags inside a UL-LI list, **but** somehow you want this to be displayed like the line-numbers are not a part of the list. This expectation is a mere contradiction. According to the HTML-Code, the way it is displayed inside the PDF is completely correct and the expected behavior.

I think I have made my frustration about the current state of the line-number-feature quite clear in the past: Working with implicit information will not work most of the time.

**Comment by emanuelschuetze** [comment]
@CatoTH Can you look at this issue please?

**Comment by CatoTH** [comment]
I made a first attempt to mitigate this problem in https://github.com/CatoTH/OpenSlides/tree/Issue2561-pdf-line-numbering-in-lists

There are a lot of limitations around this issue.
An approach that did not work: Just using negative margins for the line numbers on the left to move the line number to the left of the bullet points; this moved the bullet point as well.

So the current approach is to extract all line numbers from within a list and wrap the list with a two-column-structure: the line numbers in the left column, and the list in the right one. This works somewhat okay for plain text and nested lists. You can see the structure that's created now in the last lines of tests/karma/core/pdf.service.test.js.

However, things will be problematic, once more complex formattings (font sizes, tables, images) are used within a list, as the column to the left does not know about the height of the right one - line numbers will run out of sync with the corresponding lines in that case.
I really don't know any way to solve that. Creating a two-column-structure for each list point separately would limit the effect of this out-of-sync'ness, as it would get in sync once the next list point starts. However, OL in PdfMake doesn't seem to support a "start" attribute, so if we split the list points in a OL, the list would start with point 1 over and over again, which is not an option.

Anyway, as long as no complex formattings are used, this approach should somewhat work...

**Comment by emanuelschuetze** [comment]
Fixed with #2739.
