### ISSUE TITLE
OS 2.1: blocker: motions are deleted on saving motion block settings

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2568]
This is in my opinion a release blocker:
- create a motion block
- select 2 motions and put them into the block
- now go to the motion block list. You can see there that there are 2 motions in the block
- now click _Edit_ below the motion block name
- you can change there something or keep everything as is, just press the _Save_ button

Boom: all your motions of the block are deleted!

**Comment by donovaly** [comment]
In the motion block list one can see that after the save the number of motions in the block is zero. If one goes to the general motion list one also don't see the motions that were part of the edited block.

Now, after fiddling around for many time I realize that the motions can be restored by going to the general motion list and then press the refresh button of the browser. Very weird because without pressing refresh I could import the deleted motions and they were correctly imported as new ones. After pressing the refresh button I have now tons of identic motions because now they are all back - a very weird bug.

**Comment by normanjaeckel** [comment]
The problem is that `dsEject` in core/base.js ejects all motions when a motion block comes in via autoupdate. I do not know exactly what this factory does. It looks like that it is responsible to clean up non root rest models if a root rest model comes in. But here motion AND motion block are root rest models so this method should not trigger. @ostcar Any idea?

**Comment by normanjaeckel** [comment]
@ostcar Ping.

**Comment by donovaly** [comment]
Confirmed, many thanks.
