### ISSUE TITLE
wrong language for OS action messages

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2657]
- use English menus
- change the password of a participant

Result: OS shows this message:

![localhost 8000 2016-11-19 17-10-11](https://cloud.githubusercontent.com/assets/1828501/20456693/bad5402c-ae7b-11e6-9d57-b4f9b66dc0b2.jpg)

So the action message that the password was changed is in German, not English.

This might be a general problem with all action messages.

**Comment by emanuelschuetze** [comment]
The action messages comes from server. The server language is set by browser default lanaguage - not by the client-side changed language in OpenSlides.
So set your browser language to EN thenOpenSlides changes the  all action messages comes in EN.
I wan't fix this behaviour because we use from server translated messages very rarely in UI.

**Comment by normanjaeckel** [comment]
We can think about removing **all** server translated strings.

**Comment by FinnStutzenstein** [comment]
Or make a list of all posible strings and mark them in js. Like we are doing it now for all configs values etc. I would suggest make an strings.js, just with all string tagging.

**Comment by jsaalfeld** [comment]
This won't be an issue anymore with the openslides 3 client. If this Issue still persists, please reopen it.
