### ISSUE TITLE
Refactor caching for new objects with many 2 many fields

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2736]
The caching for new objects with many 2 many fields has to be refactored (or just fixed).

Note: There is a hotfix/workaround (see #2734) which fixes #2727. But we want a generic solution for all m2m fields.

**Comment by ostcar** [comment]
* Use transactions or
* Reload the data before sending it. Channel >=1.0.0 only sends the information to a channel at the end of a request.

**Comment by normanjaeckel** [comment]
The problem is that I want to bundle the blobs. It is not just about sending them at the end of the request cycle. I am looking for an easy way to put all blobs into a stack and then send them out later without touching every line of code in the modules (motion, assignment, ...). Maybe a new custom channel?

**Comment by normanjaeckel** [comment]
Maybe we gat a generic solution also to solve #2779.

**Comment by FinnStutzenstein** [comment]
Ping
Is this still relevant or an issue?

**Comment by ostcar** [comment]
It is so old. It can probably be closed.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Please reopen if it still relevant for you.
