### ISSUE TITLE
Pdfmake-dist is down

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2769]
See https://bower.io/search/. pdfmake-dist is down but pdfmake exists. I do not know the difference.

**Comment by miltador** [comment]
Hi there! I apologize for that.
That fork of `pdfmake` is obsolete now, all changes where merged back to [bpampuch/pdfmake](https://github.com/bpampuch/pdfmake).
While there is currently no ETA about the new release, all changes from `pdfmake-dist` where merged back.
You can try to use the current master or, if you'll encounter some issues, use `f419a18875095812b81a9a0189e52eb16a008342` revision which is pretty much the same as `pdfmake-dist@0.1.31`

**Comment by tsiegleauq** [comment]
Pdfmake is the following:
[https://github.com/bpampuch/pdfmake](https://github.com/bpampuch/pdfmake)

this was depracted since bpampuch somehow disappeared.
Therefore we used the fork:
https://github.com/pdfmake/pdfmake

Which is obsolete now. I got notified very recently, that there were found new maintainers:
https://github.com/bpampuch/pdfmake/issues/598#event-891949057
