### ISSUE TITLE
User without users.can_see permission cannot see names of submitter/speakers/candidates

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3002]
To reproduce:
* Create new (empty) group with motions.can_see permission
* Create new user and add this new group to user.
* Create new motion with admin as submitter.
* Login as user and look at the motion
=> Submitter is not visible!

* Add permission 'users.can_see' for the new user group.
* Reload as user.
=> Now, submitter ("Administroator")  is visible!

Same problem also for speakers and candidates. This is very important for 2.1 because many organizations removed the 'users.can_see' permissions for normal users!

@normanjaeckel @FinnStutzenstein Any idea how to fix it?

**Comment by FinnStutzenstein** [comment]
Technically the `users.can_see` permission does what should do. But: A submitter is strongly coupled with a motion. If a user is allowed to see this motion, he should be allowed to see the submitter. There are some levels of restrictions:

1. The server sends all users that are coupled with motions/assignments/topics/mediafiles/... They are now also visible in the list view. The user can visit the detail page.
2. The server sends all coupled users but cuts off the most data. The client just gets a mapping `id <-> Tttle, first name, last name`. The user list view does not show these users. The users are not clickable in the motions/...
3. We do not fix this and leave `users.can_see` very restrictive. If so, we have to modify some template, so that the submitters/... are not shown.

If we choose 1. or 2. the server has some more work to do to collect all needed users; so check which item the user is allowed to see and yield the users from these items.

**Comment by normanjaeckel** [comment]
Discussed with @emanuelschuetze. The user app may inform all other apps via a Django signal about every specific user and ask whether the user has to be available for the client at least with LITTLE_DATA (see users/access_permissions:get_restricted_data()). The apps my answer Yes (True) if e. g. in motion app the user appears as submitter or supporter.
