### ISSUE TITLE
Motion: Change recomondation parses HTML

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3024]
If you write HTML-Like Text in CKEditor (as text), it gets parsed in every Change recommendation view.

In Original view: Tags get displayed as plain text (as one would expect)
![bildschirmfoto von 2017-03-01 11-20-59](https://cloud.githubusercontent.com/assets/10233032/23455937/c9c01756-fe71-11e6-8269-7bb84cf0a035.png)

If we change to any recommendation view, the HTML Text gets parsed.
![bildschirmfoto von 2017-03-01 11-21-11](https://cloud.githubusercontent.com/assets/10233032/23455979/f42acf72-fe71-11e6-9a14-f540c4a4b0b5.png)

I'd expect that HTML tags gets somewhat escaped and therefore not rendered in motion view.
I simply added text and **did not use** the "source" function of CKEditor.

@emanuelschuetze

**Comment by emanuelschuetze** [comment]
It seems that motion.getTextByMode(..) (which is called from changed/diff/final version) does not escape html tags in motion text. In template we have to use `ng-bind-html` - otherwise we can show the html rendered line numbers.

@CatoTH Can you escape html tags from motion text in all versions please? I think you should know the functions where you can fix it. Thanks.

**Comment by CatoTH** [comment]
@emanuelschuetze Please review if this fixes the issue

**Comment by emanuelschuetze** [comment]
Done with #3040
