### ISSUE TITLE
Foreground color overrides background color in pdf

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3255]
Setting: Some text with a background color set and a part of this text with a different foreground color:
The web view:
![colorweb](https://cloud.githubusercontent.com/assets/8439581/26142236/02eb26c4-3ae0-11e7-8b4a-42c71afadaec.jpg)
The Pdf:
![colorpdf](https://cloud.githubusercontent.com/assets/8439581/26142246/0838e076-3ae0-11e7-8fad-c123f3046295.jpg)

In the part with the foreground color, the background color is dismissed

**Comment by tsiegleauq** [comment]
concatination of styles has been disabled for quite a while, and there is currently no intention to re-enable it again (since it is still very likely to cause side effects because of multiple html style and inline css style confusion)

Worked quite well with TinyMCE in the past (TinyMCEs html code was way cleaber, but always caused issues since CKEditor)

I am always clearing the style in every recursion. I show the line later.

**Comment by FinnStutzenstein** [comment]
Works in current master.
