### ISSUE TITLE
Motion PDF: Page break splits linenumber from text line

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3273]
Add a long example text (>3000 chars) as motion text and create the motion pdf. The page break causes that the last text line of page 1 (line 35 in our example) is moved to page 2 - but the line number ("35") is still placed on page1. See pdf example output (line 35):

![issue-page-break](https://cloud.githubusercontent.com/assets/2075427/26582020/99166fbe-453f-11e7-82ab-93d2da01ba8b.png)

Find a way to keep line number and text line together - either on page 1 or on page 2.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze This is strange. The doc definition is correct. PdfMake splits up two columns; I copied the doc definition into the PdfMake playground and there the pdf is created correctly. I checked out different versions of PdfMake, but always the same issue. I do not really know, what I can do now..

**Comment by emanuelschuetze** [comment]
possible hofix: use same font size for linenumber and text. (successfully tested) But this is not very nice...

**Comment by tsiegleauq** [comment]
Hi.
That is not really strange in my opinion ;-)

**Why does this issue appear?**

the printable space in the PDF is limited (usually by the footer). If the content exceeds the printable page, PDFmake will continue to print the text on the next page.

This is happening here because the line-number and the content got different font-sizes and are connected loosely (e.g: they are not part of a table or a column-object).

The PDF parser is significantly **older** than the line-numbering plugin, it has not been designed (yet) to work with all different kinds of line-numbering (my remarks on the code generated by the line numbering plugin for healthy PDF generation have not been considered).

The **ideal** solution would be to have a column object with the line number and the corresponding text, such as:
```
columns: 
  [
    { 
      <Zeilennummer>
    },
    {
      <Text>
    }
  ];
```

So the parser would need a slight alteration in the case of "linenumber-outside" in `<span>`

maybe altering the already existing columns and add call parse-children in column[1] is already enough.

The even nicer solution would be cleaner HTML code that has not that many space for interpretion.
