### ISSUE TITLE
Bug in restricted_data_cache

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3427]
Only save cache in `add_element` if the cache exists.

**Comment by FinnStutzenstein** [comment]
This can currupt one's cache. To recreate:
 - Delete the cache from a user.
 - Make an autoupdate that affects the user (e.g. project something)
 - reload the users browser. 

https://github.com/OpenSlides/OpenSlides/blob/4c9a8b4ec75882d6d6f02228327ba6a57eb1bd3a/openslides/utils/autoupdate.py#L82
This `build_cache_for_user` logic could be separated and called, if the user does not have a cache, if `add_element` is called.

**Comment by ostcar** [comment]
The quickfix is to add a method:
```python
    def update_element(self, user_id: int, collection_string: str, id: int, data: object) -> None:
        if self.exists_for_user(user_id):
            self.add_element(user_id, collection_string, id, data)
```
To the restricted_data_cache an use it at this line:
https://github.com/OpenSlides/OpenSlides/blob/9fd0121132c8c0a69e7a3f63fbed8b19ef3ec33b/openslides/utils/autoupdate.py#L296

The problem is, that this method is not atomic so in very rare cases it is possible, that the error still occurs. The best solution would be to use a [lua script](https://redis.io/commands/eval) instead.

**Comment by emanuelschuetze** [comment]
Done with a hotfix in #3483. Please find a better solution with implementing a cache api in #3428. Thanks.
