### ISSUE TITLE
Extend the restricted_data_cache

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3428]
- Add `del_user()`, `del_all()` to delete caches if e.g. permission changes.
- Add `build_for_user()` to (re)build the cache for a users. This should be callable from the commandline, so the cache for a big assembly can be prebuild.

**Comment by emanuelschuetze** [comment]
see also hoftix of #3427 in pr #3483

**Comment by emanuelschuetze** [comment]
@ostcar When do you could implement this cache api? In the next weeks want to release 2.2.

**Comment by ostcar** [comment]
I fixed the first part of this issue in #3600.

I don't think any more , that added `build_for_user()` to the cache is a good idea. If it would be added, it should not be used in `ws_add_site` because the current implementation not only creates the cache but also creates the `formatted_data`. So if the cache would be build in a separate function, the two for-loop have to be run twice. This would be unnecessary slow.

Another disadvantage would be, that all functions in [this code-block](https://github.com/OpenSlides/OpenSlides/blob/d185e05ab194f05214e677bb1a537d142fa75389/openslides/utils/autoupdate.py#L85) have to be imported into the cache-file.

So the solution is, that the person, who creates the management command copys all the linked lines into the management command.

**Comment by ostcar** [comment]
Can this issue be closed after #3784 is merged?
