### ISSUE TITLE
Missing autoupdate on group delete

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3455]
When deleting a group, all users in the deleted group doesn't update. A reload is necessary that all 'undefined' strings in the client disappear.

**Comment by emanuelschuetze** [comment]
It seems to be also a cache problem. Using redis a reload does not work. Deleting cache helps.

**Comment by normanjaeckel** [comment]
In the client I can see a string "unknown" but the server looks like sending a correct autoupdate, right?

**Comment by FinnStutzenstein** [comment]
Yes, all users get a deleted for the one group. But see this situation:
A user is just in one group and this group has no permissions. Then this group is deleted, so the user should get all perms of the default group. The user gets the autoupdate with the deleted group - but does not get an autoupdate with "changed: users/user" for himself. So his `groups_id` is not updated in the client, resulting in wrong permission calculation. I tried adding this in the destroy view in the `GroupViewSet`:
```
affected_users = User.objects.filter(groups__pk=instance.pk)
inform_changed_data(affected_users)
```
But the user affected by the deletion does not get updated.
This is also important for the user list view: The group selection does not work, because the client stucks at the old group and changing results in "the pk '...' does not exist"; so the manager need to get updates for all affected users, too.

**Comment by emanuelschuetze** [comment]
Similar problem when a user gets a new permission (e.g. "motions.can_see_comments"). The user see the new comment fields but without content. Also reload does not helps because the restricted user cache contains was not updated (with new comment field values). Deleting the specific cache key helps. After reload the config values are visible in OpenSlides. - The REST api already shows the correct values.

Any hints how to fix this?
