### ISSUE TITLE
enhancement: allow to export single motions to DOCX

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3556]
OS 2.2. has the nice feature to export all motions to PDF, DOCX or CSV. However, for single motions on can only export to PDF.

I am sure it would be useful to export single motions to DOCX too. Therefore one should be able to use an export dialog like the one to export all motions.

**Comment by emanuelschuetze** [comment]
DOCX export is for managers/staff group members only because normal users (delegates) should not work with an editable motion format. The idea: the staff members can export all motions (or just one if you use the motion filter) into DOCX to reworks (e.g. some layout issues) and publish motions in final export format. DOCX is just for editors not for end users. So WONTFIX.

**Comment by donovaly** [comment]
> DOCX export is for managers/staff group

You misunderstood me. I am the admin and manage the assembly. A participant asks me if I can send him a particular motion. Therefore I only want to have this single motion exported as DOCX. 

> (or just one if you use the motion filter)

This is the bug because I cannot get this to work. Even if I select in the motion list the single motion and then press on "Export all" I get all motions. therefore this enhancement request is to have for every motion at the upper right instead of the button "PDF":
![motion-export](https://user-images.githubusercontent.com/1828501/35515747-3f76b4b0-050a-11e8-8471-6993678f9a52.png)
the button "Export" that triggers the nice new dialog to select what format. This way one can use another format than PDF.
