### ISSUE TITLE
enhancement: return to actual page in agenda list

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3558]
I have an agenda that is so long that it needs 2 pages.

- click on an agenda item on page 2 to modify it
- click now on the button "back to overview

result: page 1 of the agenda is displayed and not page 2 where the item appears

I found out that it would be better to return to the actual page where the item appears in the agenda because one often has the task to modify items one after each other. If you disagree, feel free to close this as WONTFIX.

**Comment by emanuelschuetze** [comment]
This is a general issue for all list views with pagination.
@FinnStutzenstein Do you have a quick fix for this usability issue?

**Comment by donovaly** [comment]
This is not fixed in OS2.2beta2

**Comment by emanuelschuetze** [comment]
@donovaly It is fixed in 2.2b2 - I can confirm it. Maybe you have to remove your browser cache?
Please try again:
Create >25 agenda items. Go to 2nd page in agenda list view. Open an agenda item (of 2nd page) in detail view. Not go "Back to overview". => You see the 2nd page of the agenda list view - NOT the first page.
So for me it works as expected. Can you confirm it?

**Comment by donovaly** [comment]
> Maybe you have to remove your browser cache?

Now it works. Maybe it was indeed only something in the cache.
