### ISSUE TITLE
DOCX export error for motion 

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3563]
To reproduce:
1. Create a new motion with a special text: "foo & bar"
2. Create a change recommendation for line 1 and add something (e.g. "test")
3. Open export dialog, select DOCX and "final version". Download DOCX.
4. Try to open the DOCX document in LibreOffice. => Error dialog:
```
Ein Fehler trat während des Öffnens der Datei auf. Dies kann durch inkorrekter Dateiinhalte verursacht worden sein.
Die Fehlerdetails sind:
SAXException: [word/document.xml line 2]: xmlParseEntityRef: no name

Den Import fortzusetzen kann zu Datenverlust oder -beschädigung führen und die Anwendung könnte instabil werden oder abstürzen.

Wollen Sie den Fehler ignorieren und den Ladeversuch der Datei fortsetzen?
```

=> Click "Yes". The motion text (final version) is empty.

**Comment by FinnStutzenstein** [comment]
The issue comes from `motion.getTextByMode`. For the original version it returns
```<p>foo &amp; bar</p>```
which is correct HTML. For `agreed` it returns:
```agreed <P>foo & bar test</P>```
This HTML is not valid.

Because the DOCX internally is XML, it has the same "problems" like HTML. You need to escape entities like `&` to `&amp;`. I would suggest, that `getTextByMode` should return valid HTML.
@CatoTH Can you have a look?

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze If you need a hotfix let me know!
