### ISSUE TITLE
impossible to make several inline edits in a row

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3673]
In an assembly I had the case that people requested a change. I used inline editing, the assembly voted yes. Now a participant requested another change.

result: I could not do this. There is no button anymore to make an other change. But several changes for one motion are something normal.

**Comment by tsiegleauq** [comment]
I don't get what this is about. Users can easily make changes, even to motions that are technically done and changes can also be edited.

**Comment by emanuelschuetze** [comment]
The requested feature is: allow multiple change recommendation per line. Currently, only one CR is possible per line/line range. This is good enough because generally a comittee makes only one proposal. If several users suggest several variants then amendments are the right solution.
So this can be closed.
