### ISSUE TITLE
Projector not starting

### ISSUE THREAD

**Issue by olgru** [OpenSlides/OpenSlides#3819]
Hi all.

Sorry that I wrote it here - maybe it's not an issue at all, just a configuration problem on my side. However I didn't really found a forum to address my kind request for help.
I installed openslides 2.2 on a raspberrypi 3 and it works well. Then I tried to configure the HDMI port to be the projektor 1 by autologin, startx und using midori in fullscreen to load loalhost:8000/projector/1/.
This works too.
After this I replaced the db.sqllite3 with another file from another openslides test system. I reboot the PI and since then it displays "Der Projektor kann nicht geöffnet werden." I can open the projektor from other computers.
So I assume that there is something, somewhere in cache which conflicts with the initial projector configuration. I delete all midori related cache files which I could found, and tried again - no success.
Here are my questions:
- Isn't there somewhere a log which I can consult to see more than "Der Projektor kann nicht geöffnet werden"?
- Is there anything else I can look for?

Thank you in advance for your help!

Cheers,
Oliver

**Comment by jsaalfeld** [comment]
HTo see the projector as a non-logged-in user (aka anonymous) you have to activate in you localhost:8000/users/groups the "Can see the projector" permission for "Default". Otherwise you have to be logged in as a user to see the projector. If this permission is not ticked, you will see the message "Can not open the projector" if you try to open it.

You can test this in the https://demo.openslides.org/ instance.

**Comment by olgru** [comment]
Thank you.
Indeed the permission was correctly set. But your comment forces me to re-check the permission in the general settings. "Allow access for anonymous guest users" was disabled - I think I did this because I misunderstood that this flag does not automatically provide access to the system. 
Anyway - issue solved! 
Again many thanks for the quick hint.
Have a nice day,
Oliver
