### ISSUE TITLE
Angular/Material compatible mobile friendly rich text editor

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3875]
At some point we need to decide for a rich text editor. This might be a little research task.

The Requirements are:
- Angular compatible
- Material UI compatible
- mobile friendly (or somewhat usable at least)
- using a free license, MIT prefered
- the HTML output should be absolutely predictable - this is extremely important for the Diff view algorithm, line numbering and PDF export.
- Copy-Paste from microsoft word _should not break the layout too much_:tm:

We have been using [CKEditor](https://ckeditor.com/) successfully for some time now.
CKEditor is proprietary software but offering free licenses for OpenSource/Free Software projects.

CKEditor 4  (what we are using now) is installable in Angular using [this github project](https://github.com/chymz/ng2-ckeditor), which is somewhat outdated.

CKEditor 5 [supports Angular projects directly](https://github.com/ckeditor/ckeditor5-angular)

TinyMCE, we used that in the past, also [supports angular projects directly](https://github.com/tinymce/tinymce-angular) and offers a community edition under [LGPL](https://www.tiny.cloud/download/self-hosted/)

There certainly are other projects that might be suficcient for our requirements and might fit our needs.
[ngx-wig](https://github.com/stevermeister/ngx-wig), [ngx-editor](https://github.com/Sibiraj-S/ngx-editor) and more.

**Comment by FinnStutzenstein** [comment]
I still prefer the CKEditor. Lets wait for @emanuelschuetze . Maybe we will get a different license.

**Comment by jsaalfeld** [comment]
Related to #3904

**Comment by jsaalfeld** [comment]
The most viable alternatives are
**[Trumbowyg](https://alex-d.github.io/Trumbowyg/)** - [GitHub](https://github.com/Alex-D/Trumbowyg): It has nearly the same features as CKEditor in Version 4 and produces a clean and viewable HTML output. Since it it licenced under MIT, it is compatible with our licence.

**[TinyMCE](https://www.tiny.cloud/)** [GitHub](https://github.com/tinymce/tinymce): This seems the most widespread (next to CKEditor) editor in this context. It is licenced under LGPL and is therefore compatible with MIT. But it seems that they are heading the same way as CKeditor and therefore there is a small uncertainty in the future. The full editor has some nice features and looks very promising on the feature side and has a manipulatable HTML output.

Other Editors, like [AlloyEditor](https://alloyeditor.com/), [QuillJS](https://quilljs.com/) or [SummerNote](https://summernote.org/) don't have a fitting licence model, no way to manipulate the HTML in the editor itself or just don't have the needed features in the editor.

**Comment by tsiegleauq** [comment]
was resolved by #4027. We decided to use TinyMCE
