### ISSUE TITLE
Caching framework? [discussion, v3]

### ISSUE THREAD

**Issue by CatoTH** [OpenSlides/OpenSlides#3900]
To prevent recalculating the Linenumbering / Diff with each iteration, we need a cache. In Angular 2, we used https://docs.angularjs.org/api/ng/type/$cacheFactory.Cache .
Is the linenumbering / diff the only component in need of this? If so, a simple hash object stored in memory should be enough. If we need a more general and flexible solution, we might want to use a module like https://github.com/fulls1z3/ngx-cache or https://github.com/jmdobry/angular-cache .

**Comment by FinnStutzenstein** [comment]
Currently we use https://www.npmjs.com/package/@ngx-pwa/local-storage. It's asynchron but uses indexed db. Also we have a cache service wrapping this API (it has an internal queue, because if you set an item too fast, that the previous set-operation is not finished, you get an error). Currently used to cache the whole data store.

**Comment by tsiegleauq** [comment]
I don't think caching will be needed. Virtual scrolling should be fast enough :tm: to handle the list of amendments. I was planing to alter the concept of amendments a little to store the linenumbers and diff-lines, that should prevent unnecessary recalculation.
