### ISSUE TITLE
Agenda race conditions

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3971]
The client currently cannot resolve race conditions.

Race conditions appear when, i.e, the user creates a new topic which will automatically create a new agenda item.
It seems to be random whether the agenda item or the content object occurs first per auto update.

In a current PR I added warnings when there was missing data due to race conditions to address these issues.

**Comment by FinnStutzenstein** [comment]
This is not a race condition: an item and the content object are as loosly connected as e.g. motions to categories.

Two scenarios:
A)
1. The content object (co) comes in first
2. The item comes in later

The co is inserted in the DS. Then the item comes in. The repo creates a viewItem with the item and co stored in it. Ready for the views.

B)
1. First the item
2. Then the content object

The item gets inserted and the viewItem is created. The co is not found, so it stays by null. This is perfectly fine (see below). Then the co gets inserted. The item repository updates the viewItem and sets the co. There might be a little lag in the view, because for a short time there is no co. But both objects are in fact in the same autoupdate, so this is really fast.

Both scenarios are equal to motions/categories when you consider the loading phase of the client. The order of motion and category is also undefined.

Why it is fine, that an item has no content object? I should be more precise: every item has a co-Identifier (meaning the collection string and id). But a client may not be allowed to see the co itself. One example is a user who has not the permission to see assignments, but there are items with assignments as co. The user can see the items, but they do not provide a link to the detail view etc. In code, the user has the co-identifier, but not the assignment itself.

Then, some time later, an admin grants the user the permission to see assignments. What happens? The server sends all assignments to the user. Then the exact same case as described in B) happens: The item repo updates the viewItem and sets the assignment as the co.

So, we do not depend on having one object, if the other is given. This situation is nowhere in the client. Just make the updating of the view models correct on autoupdates, then there are no problems.

Hope, this explains this well.

**Comment by tsiegleauq** [comment]
Solved using a better repository observers
