### ISSUE TITLE
npm build does not add css images

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#4083]
When I start the client using `npm build` the client does not include css images. It looks like this:
![build](https://user-images.githubusercontent.com/977937/50438501-864de000-08ee-11e9-9434-ed6d6d007bd0.png)

When I use `npm start` it looks like this:
![start](https://user-images.githubusercontent.com/977937/50438511-95349280-08ee-11e9-912c-c7a1b64cb13e.png)

(When I write `npm build` I mean `npm run-script build`. `npm build` does not work at all)

**Comment by jsaalfeld** [comment]
`npm build` can't and shouldn't work, because the build-command (like `test` etc.) is a script defined in the `package.json`. Therefore you should run `npm run build`. `npm run build`, unlike `npm start`, does not a start a webserver, it just compiles the webclient, so it can be shipped by third-party software. `npm start` runs a development-web-server.

The build files will be in the `openslides/static/` folder (not `openslides/client/static`). After that you'll need a web-server (do _not_ use `daphne` or `gunicorn`, those are not configured for the job!). You can i.E. use `nginx` or apache with the according configuration. You can take a look at the https://github.com/OpenSlides/openslides-docker/tree/master/compose-big-mode for a working configuration.

**Comment by tsiegleauq** [comment]
> I don't want to code javascript.

Nobody does, that's why we use TypeScript ;-)

> So it would be nice, if the images would also be copied to static folder

They are. `~/OpenSlides/openslides/static/assets/img`
`npm build` simply has to be replaced with `npm run build`

**Comment by jsaalfeld** [comment]
> I don't want to code javascript. I just want to code python. Therefore the build-script was added, that a python developer does not have run the npm development server. So it would be nice, if the images would also be copied to static folder

As @tsiegleauq and I wrote, they are available in the root folder under `openslides/static`. Neither I, nor @tsiegleauq have an idea what to change in the daphne setup, so it delivers the correct contents. Since we don't need the `daphne` or `gunicorn` to deliver anything we were happy with the dev-server solution (@FinnStutzenstein develops on the server in this way as well). I updated the `DEVELOPMENT.rst`.

**Comment by ostcar** [comment]
This is still not fixed. The issue here is, that daphne does not show the images. You can unassign yourself, but please do not close this issue until it is fixed.

**Comment by jsaalfeld** [comment]
The real question is: Is this still a valid usecase that should be cared about? Since the dev-office doesn't use daphne to ship the contents of the client (and it is not recommended in any way), should work be invested to reconfigure the daphne/gunicorn to ship the static files again?

**Comment by ostcar** [comment]
If you wan't me to test the client when I code in python, it should be fixed.

In the paste, you could run openslides without installing nginx. I think it is still a nice feature to do this. There are not only big assemblies. I used openslides often in the past only to present something. It would be pity if this would not be possible anymore with a simple `pip install openslides`.

**Comment by tsiegleauq** [comment]
@ostcar If you feel there is something to be fixed, set the title, the description and the keywords accordingly. The productive build of the client ships all necessary images and CSS files.

**Comment by jsaalfeld** [comment]
I understand the need, that this way should work again. Therefore I extracted the requirements of this issue and wrote it into a new issue (#4091), which will serve as a point of tracking the issue.

**Comment by ostcar** [comment]
thx
