### ISSUE TITLE
unrecognized ChangeRecoMode option

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#4108]
Sometimes:tm: opening a motion results in an error.
It's pretty hard to reproduce but seems somewhat related to ChageRecoMode.

```
push../src/app/site/motions/services/motion-repository.service.ts.MotionRepositoryService.formatMotion | @ | motion-repository.service.ts:336
```

**Comment by FinnStutzenstein** [comment]
Your first point is wrong: a view model should not hold any information from components, because it's a unique object through the hole page and not der component. Also these view models are deleted and recreated on autoupdates. You can test this, if you have two tabs. In one you show e.g. the diff view. Fhen update the motion to issue an autoupdate -> the view is changed from diff to normal.

What you proposed is the correct way! Please move those attributes to the component, and also cr_mode, ln_mode etc.

**Comment by CatoTH** [comment]
I've changed it accordingly
