### ISSUE TITLE
support typescript 3.3 or install a smaller version

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#4249]
When I run 
```
npm install
npm run build
```
I get the message: `ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.3.1 was found instead.`

When I call `npm install typescript@">=3.1.1 <3.3"` everything works fine.

Either TypeScript 3.3.1 should be supported or a supported version should be installed.

**Comment by tsiegleauq** [comment]
Cannot reproduce your issue.
I updated our angular stack last week, did you remove `client/node_modules` before `npm install`?

**Comment by jsaalfeld** [comment]
I tried this on an old checkout and could reproduce this error. The old checkout however, had old dependencies. As soon as I updated, removed my `client/node_modules` folder and rerun `npm install && npm start` I encountered the same issue.

I wonder why travis doesn't fail.

**Comment by tsiegleauq** [comment]
https://github.com/angular/angular/pull/28497

**Comment by jsaalfeld** [comment]
it seems to be a `semver` issue, since `semver` decides wether a version is compatible or not (which is indecated with the caret in front of the version.

My local installation of `semver` is version `5.6.0`, but the local version in `OpenSlides/client/node_modules/semver/bin` is `5.5.0`. Which may causes the issue.

@ostcar, @tsiegleauq  and @MaximilianKrambach - may can you all provide the versions of semver in your system (just call `semver` somewhere in your system) and the version of semver in openslides (call the bin in the `semver` folder in `node_modules`?

**Comment by tsiegleauq** [comment]
Local semver: 5.6.0
NodeModules semver: 5.5.1
