### ISSUE TITLE
Wrong autoupdate for permission toggle

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#4328]
1. Login as admin and create normal user (e.g. with group "delegates")
2. Login as normal user in private tab
3. As admin: Go to group matrix view
4. Remove permission "Can see names of users" for group "delegates"
   -> for normal user: menu entry "participants" removed  (OK)
5. Readd permission "Can see names of users"
   -> for normal user: menu entry "participants" NOT readded
   -> for admin: get statuscode 200 and autoupdate -> checkbox is now _activated_  (FAILURE)
6. As admin: Reload group matrix
    -> now persmission "Can see names of users" is deactivated

Something with the (delete?) autoupdate seems wrong on server...

**Comment by ostcar** [comment]
I found the error. I am not sure how to solve it. It is in a part of the code, that I don't like at all https://github.com/OpenSlides/OpenSlides/blob/master/openslides/users/views.py#L367:L386

The permission is saved successfully. The cache is not updated immediately, because this happens only at the end of the request (autoupdate_bundle). Then, the problematic code asks via a signal  for some Elements, that are affected be the permission change. When the "users.can_see_name" permission changes, then the user app returns all of its data, to the autoupdate system. This includes the group, that was changed. But the data is not read from the database but from the cache (that was not updated). So the not updated group is send via autoupdate to the clients.

A quick hack to solve this would be, to remove `self.get_object()` from the list of elements.

**Comment by ostcar** [comment]
I found the error. I am not sure how to solve it. It is in a part of the code, that I don't like at all https://github.com/OpenSlides/OpenSlides/blob/master/openslides/users/views.py#L367:L386

The permission is saved successfully. The cache is not updated immediately, because this happens only at the end of the request (autoupdate_bundle). Then, the problematic code asks via a signal  for some Elements, that are affected be the permission change. When the "users.can_see_name" permission changes, then the user app returns all of its data, to the autoupdate system. This includes the group, that was changed. But the data is not read from the database but from the cache (that was not updated). So the not updated group is send via autoupdate to the clients.

A quick hack to solve this would be, to remove `self.get_object()` from the list of elements.

@normanjaeckel what do you think?

**Comment by normanjaeckel** [comment]
Yes. Let's remove the updated group from the list of elements.

**Comment by tsiegleauq** [comment]
@ostcar what's the current state here? Is this relevant for 3.1?

**Comment by FinnStutzenstein** [comment]
I tested emanuels scenario and it seems to work. I'll close this and if something similar happens, a new issue can be opened.
