### ISSUE TITLE
Redis sessions timeout causes logout

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#4555]
@FinnStutzenstein Can you have a look at this problem?

See https://github.com/martinrusev/django-redis-sessions/issues/60 and https://github.com/martinrusev/django-redis-sessions/issues/62.

Maybe we can use the RETRY settings or even increase the timeout to avoid django to kill clients session cookie (to cause logout for the clients.

**Comment by FinnStutzenstein** [comment]
Yes, we can try this. My problem is that I had a hard time reproducing this issue. I tried the `CLIENT PAUSE <ms>` command in redis (with a loooong timeout) and reloading the browser. As for serving initial requests the cache is needed (e.g. to build the WhoAmI response), I ran into warnings similar to this one:
```
Application instance <Task pending coro=<SessionMiddlewareInstance.__call__() running at /usr/local/lib/python3.7/site-packages/channels/sessions.py:179> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f8ce023b048>()]>> for connection <WebSocketProtocol client=['172.21.0.3', 40086] path=b'/ws/'> took too long to shut down and was killed.
```
So I didn't even get answers form the server and (maybe) a 502 Gateway timeout. I'm not sure what to do to provoke these timeouts explicitly for the session request.

I understand this problem, but I cannot test this. I would suggest to add both settings to our settings with retry=True, timeout=1, to see if this helps in production...

@emanuelschuetze Can you add those to the custom builds?
```
SESSION_REDIS_SOCKET_TIMEOUT=1
SESSION_REDIS_RETRY_ON_TIMEOUT=True
```

**Comment by FinnStutzenstein** [comment]
Update: I can reproduce the issue now. A normal `runserver`, login the client (startet with `yarn start` to simulate the nginx -> just actual requests and no static-file-requests are passed to daphne), issue `client pause 10000` in redis-cli and reload the client. With the first request (`servertime/` in my case), the server clears the session cookie. After the whoami, which is delayed, because it waits for redis to process the actual request, the client realizes, that it is logged off and redirects the user to the loginpage.

[This line](https://github.com/django/django/blob/master/django/contrib/sessions/middleware.py#L38) does the deletion (as pointed out in https://code.djangoproject.com/ticket/29203). Somehow, `empty` is `True`. I guess (need to read more code..) that it is not waited for redis (maybe synchronous code?) and there is no response, which gets interpreted as empty.

I currently does not know what to change, or where. It can be this middleware directly or the point, where redis is asked for the session. The both meantiones settings (timeout and retry_on_timeout) doesn't have any effect.

Maybe @ostcar can also reproduce this.

**Comment by FinnStutzenstein** [comment]
More updates: I read more code and looked what exactly happens: redis session [tries to load](https://github.com/martinrusev/django-redis-sessions/blob/master/redis_sessions/session.py#L110) the session and there a `Timeout reading from socket` exception occours. A few lines below, the sessionstore is cleared, which led to the `empty=True`. Then I noticed, that I had a typo in `socket_timeout`. Set this to more than 10 seconds (I have a `CLIENT PAUSE 10000`) resolves this issue. In production use this might be set below this.

I made a small PR settings the timeout to 2 seconds (somewhat arbitrary, the production use will show..)
@emanuelschuetze Please add this to all production servers.

**Comment by emanuelschuetze** [comment]
Already done.
