### ISSUE TITLE
Export all PDFs

### ISSUE THREAD

**Issue by TheJoKlLa** [OpenSlides/OpenSlides#5201]
**Is your feature request related to a problem? Please describe.**
We all ways reset our Openslides instance every new parlament session and we have to export all PDFs Files(Agenda, Elections, Motions) to archive all in paper.

**Describe the solution you'd like**
An Button to export all PDF files in an ordered and numeratet PDF with all additional informations about the session.

**Describe alternatives you've considered**
Export all PDFs manualy and add on an extra paper with the information about the present participants

**Comment by emanuelschuetze** [comment]
We want to implement this with a new protocol feature - in OpenSlides 4.1. Which should work similar like our old [OS2 protocol plugin](https://github.com/OpenSlides/openslides-protocol)

**Comment by Digivoter** [comment]
Thx for the very helpfull outlook on implementing this in OpenSlides 4.1! 
Its proabably a silly "none-programmer" idea: How much efford would it be to "copy/paste" and adopt the export functionality being available to the motions menu already today  towards the agenda menu. This would allow to select both: agenda items and motions (as well as elections?!) and enter other relevant header data (for the protocolls - as like participants lists) by one or more hidden agenda point to any position within the entire protocoll pdf under the current Version 3.x ... this way the system would meet the "must have requirements" of city parlaments etc. already to "today" THX

**Comment by tsiegleauq** [comment]
@Digivoter 

sorry for necrobumping, just saw your question:

> How much efford would it be to "copy/paste" and adopt the export functionality being available to the motions menu already today towards the agenda menu. This would allow to select both: agenda items and motions (as well as elections?!) 

a lot. But most of the work will be conceptual, since neither agenda items, topics not assignments support export options the same way motions do.

**Comment by Digivoter** [comment]
Thx Sean!
Meanwhile we have a work around for this.
We will work from the motions menu only.

So everything can be exported to one pdf...
agenda items are treated as motions (Text and Title only) with no voting etc. but with the whole comfort of agenda menue... 


Yes we thereby loose the tracking of done agenda points and the comfort of agenda details or the timing (which was deactivated anyway) but currently working from motions only, is the only way to "automatically" generate an almost perfect "minutes of the meeting" in german we call it "Protokoll" or is some cases "Niederschrift".


anyway again; thank you very much for answering my question!
Best regards
Bernd (alias Digivoter)















Original Message processed by david® 
Re: [OpenSlides/OpenSlides] Export all PDFs (#5201) 1. Juli 2021, 14:08 Uhr 
Von Sean 
An OpenSlides/OpenSlides 
Cc (2) Digivoter|Mention 


@Digivoter
sorry for necrobumping, just saw your question:
How much efford would it be to "copy/paste" and adopt the export functionality being available to the motions menu already today towards the agenda menu. This would allow to select both: agenda items and motions (as well as elections?!)
a lot. But most of the work will be conceptual, since neither agenda items, topics not assignments support export options the same way motions do.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

To: ***@***.***
    ***@***.***
Cc: ***@***.***
