### ISSUE TITLE
Rename mediafile

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5214]
I would like to split up mediafile model into two new collections.

The proposal in models.txt for the new one is `resource` so we can use `attachment` for the "old" one. The wording `mediafile` will disappear - maybe we use "file" to both, resources and attachments when talking about delivering such files by an extra service.

**Comment by normanjaeckel** [comment]
If yes, please relate this to an openslides_backend issue so I do not forget to rename the models there.

**Comment by FinnStutzenstein** [comment]
Hm, I use the word mediafile to relate to `file` and `directory`. So a mediafile can be one of them. In my opinion we can keep files and directories mixed (this would reduce work in the client a lot). I do not like `attachement`, because a mediafile might not be a file nor an attachement. From the usage it is more like "user defined staticfiles". I like the term "media" to separate these files from staticfiles or resources (btw. resources do not have a folder-structure, so there it is clear that a resource is a file). But whether `mediafile` is a good name - i don't know.

**Comment by FinnStutzenstein** [comment]
No, you cannot upload one, but create one in OpenSlides.

**Comment by normanjaeckel** [comment]
So we need a better name for this chameleon object that can hold a structure for itself or hold a users uploaded file that can be uses as attachments or as unattached file. The current implementation really looks like being grown under other preconditions (small budget or no time ...).

**Comment by normanjaeckel** [comment]
@emanuelschuetze I would like to have a decision here so that we can name or rename the object to the correct (new or old) wording.

**Comment by FinnStutzenstein** [comment]
> The current implementation really looks like being grown under other preconditions

Nope, we did some planning for this structure. This was the best result of some (I remember having more than 4 modelings) proposals. Maybe the name "mediafile" can be changed, but we do need a name, that keeps the meaning of both usages and seperates from static and resource.

**Comment by normanjaeckel** [comment]
There is no issue or pull request that shows some proposals with their advantages and disadvantages. Maybe someone can explain why the directory structure should be merged with the files itself.
