### ISSUE TITLE
Moving amendment paragraphs to new collection

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5215]
What do you think about moving the amendment paragraph feature to a new collection so we do not have to deal with an unknown number of motion fields here? (I know that we have this problem for users again, but I assume we can reduce complexity if we only think about a special logic only for our 2 million users which live under the big organisation but as an abstract logic for potentially all collections.)

**Comment by FinnStutzenstein** [comment]
I'm ok with rethinking this structure. But this separation will result in client work, that I cannot estimate, how big it would be. And I do have a more general concern here:

The structuring of fields will be present in more models. This is one of our new main advantages of the flexible model structure. The backend must be able to handle this not only for users. I dont like handling users special, just because there will be many of them (Imho there will be more motions than users after a few years). Currently, we are not using this feature as much, becuased we sticked to the old structure fairly strong (to keep work in the client low), but with new features or later reorganisations, I'm more than confident, that this will be used more frequently.

**Comment by tsiegleauq** [comment]
Since version 2 I'd rather have amendments (not just amendment paragraphs) in an own collection and an own class.

However, altering this structure now would be extra overhead that I would advice not to tackle at the moment.
