### ISSUE TITLE
OpenSlides4 Documentation get_many

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#5397]
In the documentation it says, that datastore.reader.get_many returns `Map<Collection, Map<Id, Partial<Model>>>`

But actually, it returns Map<fqid, Partial<Model>>

Either the documentation or the code is wrong.

**Comment by jsangmeister** [comment]
Yes, I noticed that as well. Forgot to implement this when changing they way get_many works. The documentation is correct (we discussed that we wanted it that way if i remember correctly?) and the code is fixed in https://github.com/OpenSlides/openslides-datastore-service/pull/46

BTW, please assign either me or @FinnStutzenstein for datastore related issues or you run the risk of not getting an answer :D
