### ISSUE TITLE
Cannot change FROM_EMAIL after creation

### ISSUE THREAD

**Issue by leonfc** [OpenSlides/OpenSlides#5441]
**Describe the bug**
The `DEFAULT_FROM_EMAIL` (env var in docker-compose) is saved to the instancecfg database, encapsulated in `settings.py`, encoded as hex.

**How to Reproduce**
Start new instance via docker-compose file, then change the `DEFAULT_FROM_EMAIL`, run `docker-compose up -d`, and trigger an email notification. The email will be sent from the old address.

**Expected behavior**
The new email address will be used as from-address.

**System information**

- OpenSlides-Version: 3.2
- Python Version: 3.7.7
Device/Browser version not relevant

**Additional context**
Migrated from (now) legacy via export/import scripts.

**Comment by leonfc** [comment]
The "problem"/thing I didn't realize at first was that the DEFAULT_FROM_EMAIL was saved in the instancecfg database. So no problem here if the instance was set up with the correct email to begin with, which I stupidly forgot. After decoding the text, changing the email settings, re-encoding it, updating the database dump and restoring it, everything is working now. If someone needs a more detailed description of the steps, feel free to contact me.
Is there an easy way (in proportion to the benefit) to fix this, e.g. by checking the environment variable on each startup?

**Comment by FinnStutzenstein** [comment]
Hi,

(Note: this issue is related to https://github.com/OpenSlides/openslides-docker-compose)

good news: we are currently redoint the productive setup: https://github.com/OpenSlides/OpenSlides/pulls
It will be the behaviour, that changing an env varible in the `docker-compose.yml` will reflect in the containers, if they are restartet. But this will take a few weeks until this transition is done (We move the main `docker-compose.yml` setup into this repo).

You can still fix this with you current version. Exec into the server container as root when the setup is up and running. Modify `/app/personal_data/var/settings.py` to your needs. than execute `openslides-config add /app/personal_data/var/settings.py` (I hope this command is correct). With this command the settings.py gets updated in the database. Than restart the server.

**Comment by leonfc** [comment]
Ok, sounds good! Thanks for improving/redoing this!
I guess we can close this issue then, can we?
