### ISSUE TITLE
Support django-auth-ldap

### ISSUE THREAD

**Issue by joshuabach** [OpenSlides/OpenSlides#5457]
**Describe the bug**

Premise: When using [django-auth-ldap](https://github.com/django-auth-ldap/django-auth-ldap/) to authenticate via an external LDAP server, the `User` ist automatically created in Django when logging in for the first time. 

Configured like this OpenSlides will show `"Fehler: Ein Serverfehler ist aufgetreten. Bitte kontaktieren Sie den Administrator."` on the logon screen. The log shows:

```
django_auth_ldap Initiating TLS
django_auth_ldap search_s('ou=people,dc=example,dc=org', 2, '(&(objectClass=Foo)(cn=%(user)s))') returned 1 objects
django_auth_ldap Creating Django user XXX
django_auth_ldap Populating Django user XXX
[..]
openslides.requests.errors [Gsrh] /apps/users/login/ 4 unknown exception: 'NoneType' object is not subscriptable
django.request Internal Server Error: /apps/users/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/openslides/utils/rest_api.py", line 145, in handle_exception
    return super().handle_exception(exc)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/openslides/users/views.py", line 804, in post
    return super().post(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/openslides/utils/views.py", line 32, in method_call
    return Response(self.get_context_data())
  File "/usr/local/lib/python3.7/dist-packages/openslides/users/views.py", line 843, in get_context_data
    context.update(self.get_whoami_data())
  File "/usr/local/lib/python3.7/dist-packages/openslides/users/views.py", line 756, in get_whoami_data
    auth_type = user_full_data["auth_type"]
TypeError: 'NoneType' object is not subscriptable
```

When investigating further, the `User` is fact created in the Datasbase (table `users_user`), but not visible in OpenSlides [/users](https://nightly.demo.openslides.org/users).

When running revision fd026e165, the issue only occurs on first login - which fails with above error -  but when clicking Login again immediatly afterwards, it suceedes. After updating to eeb97c44f, the issue persists on multiple tries clicking Login, but can be fixed by restarting OpenSlides (then login works immedialty then, if the user already tried to login before the restart).

**EDIT:** Just to confirm, after downgrading to fd026e165 I got the old behaviour (first login fails, second suceedes) again. If you think it helps, I can do a git-bisect, however the issue was (in some form) even there before fd026e165.

**How to Reproduce**

- Checkout eeb97c44f, and build it, as described in DEVELOPMENT.rst
- Install `django-auth-ldap` package
- Add the following to settings.py:
```python
import ldap
from django_auth_ldap.config import LDAPSearch, NestedGroupOfUniqueNamesType

# Use LDAPBackend for ldap auth and group sync.  Keep ModelBackend around for per-user permissions
# and local admin user
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'django_auth_ldap.backend.LDAPBackend',
)

# Bind against directory
AUTH_LDAP_SERVER_URI = 'ldap://ldap.example.org'
AUTH_LDAP_START_TLS = True

# Search with service account & bind with user account
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    'ou=people,dc=example,dc=org', ldap.SCOPE_SUBTREE, '(&(objectClass=Foo)(cn=%(user)s))'
)
AUTH_LDAP_BIND_DN = 'cn=openslides,ou=accounts,ou=ldap,dc=example,dc=org'
with open('{}/ldap.example.org.passwd'.format(OPENSLIDES_USER_DATA_DIR)) as f:
    AUTH_LDAP_BIND_PASSWORD = f.read().strip()

# Mirror relevant groups to Django models
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    'ou=groups,dc=example,dc=org,
    ldap.SCOPE_SUBTREE,
    '(objectClass=Bar)',
)
# Resolve recursive group membership
AUTH_LDAP_GROUP_TYPE = NestedGroupOfUniqueNamesType()

# Populate the Django user from the LDAP directory
AUTH_LDAP_USER_ATTR_MAP = {
    'first_name': 'first_name',
    'last_name': 'sn',
    'email': 'mail',
}

# Cache disabled for testing
AUTH_LDAP_CACHE_TIMEOUT = 0

```
- (Re-)start OpenSlides
- Open in Browser, try to login with user that exists in LDAP, but has never been seen by OpenSlides
- _Login fails_ (times `n`)
- Restart OpenSlides and try again
- _Login suceedes_
- (Can be repeated by deleting user in OpenSlides and trying again)

**Expected behavior**

The user should be visible in  [/users](https://nightly.demo.openslides.org/users) immediatly after first login and first login should be sucessful.

**System information**

- OpenSlides-Version: `git describe --tags`: 3.1-386-geeb97c44f
- Additional version information (if any): eeb97c44fd5e5fab995591dda7d779ef5533bebf
- Python Version: 3.7.3
- `django-auth-ldap` Version: 2.1.1
- Device: Server: VM; Client: Notebook
- OS: Server: Debian 10 Buster; Client: Arch Linux
- Browser: Firefox
- Browser-Version: 78.0.1 (64-bit)

**Additional context**

The Problem seems to be that the user is correctly created in the DB, but OpenSlides uses some sort of cache, so the new user does not become immediatly visible to OpenSlides, probably since the latter assumes, that the user already existet prior to logging in.

**Comment by FinnStutzenstein** [comment]
Hi,

If you had ask, I would have told you, that just using something compatible to Django will not work with OpenSlides. Your experienced behavior is completely resonable and correct in the sense of how OpenSlides work. We are using Django only for it's ORM and application bootstrapping, but OpenSlides itself hasn't a lot in common with django anymore (this changed form 1.X->2.X and diverged constantly since then).

I'm not sure, if "bug" is the right term for something that is not designed to work with OpenSlides doesn't work. I'll put it as a feature.

Ok, now a bit technically: What is missing is the part where the created user is put into the cache. When you flush the cache/restart the server (this depends on your setup), the cache is rebuild with the data from the database. Then the new user is put into the cache and OpenSlides works fine. Note: Even if the login somehow worked and the user is not in the cache, building up a WebSocket connection won't work since auth on the WS is explicitly bound to the cache.

This one is easy to fix in the plugin, since a good places `inform_changed_data` will to the magic (e.g. see the login in the saml auth https://github.com/OpenSlides/OpenSlides/blob/master/openslides/saml/views.py#L149). Another point is, that OpenSlides does not support different AuthBackends. We have an own implementation for this. I do not know `django-ldap-auth`, but I guess there is more todo than putting newly created users into the cache.

If someone wants to port the plugin to be compatible with OpenSlides, please feel free to create a fork of the plugin and explictly ping me or another dev. If it works good, we can include it into this repo. We did this with a former SAML plugin, too.

Greets

**Comment by joshuabach** [comment]
> I'm not sure, if "bug" is the right term for something that is not designed to work with OpenSlides doesn't work. I'll put it as a feature.

Completely fine by me, this is probably a better way to label this. Considering this, I should probably be surprised that my LDAP setup even works at all ^^
 
> This one is easy to fix in the plugin, since a good places `inform_changed_data` will to the magic (e.g. see the login in the saml auth https://github.com/OpenSlides/OpenSlides/blob/master/openslides/saml/views.py#L149).

Good hint, thank you for that. I tried
```python
@receiver(populate_user)
def inject_user_into_openslides_cache(sender, **kwargs):
    user = kwargs['user']
    user.save()
    autoupdate.inform_changed_data(user)
```

(`populate_user` is a signal from `django_auth_ldap`)

but that didn't work. It seems as though the `inform_changed_data` has no effect. Even when executing  a `inform_changed_data(User.objects.get(id=foo))` immedaitely before https://github.com/OpenSlides/OpenSlides/blob/master/openslides/users/views.py#L753 (using ipdb), it does not work (The user exists in the DB at this point).

> Another point is, that OpenSlides does not support different AuthBackends. We have an own implementation for this. I do not know `django-ldap-auth`, but I guess there is more todo than putting newly created users into the cache.

Indeed, I have also encountered another problem with my setup: When django-auth-ldap auto creates a new group on LDAP login, it only creates the `django.contrib.auth.models.Group`, not the `openslides.users.models.Group` subclass. However, I was able to work around this using:
```python
@receiver(post_save, sender=DjangoBuiltinGroup)
def auto_create_group_subclass(sender, **kwargs):
    if kwargs['created']:
        group = OpenSlidesGroup(group_ptr=kwargs['instance'])
        group.__dict__.update(kwargs['instance'].__dict__)
        group.save()
```

(Putting this here just for reference)

> If someone wants to port the plugin to be compatible with OpenSlides, please feel free to create a fork of the plugin and explictly ping me or another dev. If it works good, we can include it into this repo. We did this with a former SAML plugin, too.

What exactly do you mean with "the plugin"? Currently, I have not written any OpenSlides plugin, i have just the django-auth-ldap config in settings.py above. 

So I assume the correct way to integrate `django-auth-ldap` with OpenSlides is by writing an OpenSlides plugin that does exactly that?

Thanks for the help.

**Comment by FinnStutzenstein** [comment]
Hi, a plugin is nothing else than a django app, so it is a interchangeable term. By adding `django-ldap-auth` to the installed apps, it is nothing more than adding a plugin. We had plugins (and still supporting them in the server in OS3), because it's just an additional app.

You may find useful information here: https://github.com/OpenSlides/openslides-example-plugin. It may be a bit outdated. The newest plugin is the openslides-voting-plugin. Just ignore the client. The server didn't changed much, so it should be a decent guide.

Your snippes looks good and reasonable, but if it still doesn't work I cannot help you much since I do not know django-ldpa-auth and ldap in general.

**Comment by CodeCrafter912** [comment]
Are there any updates on this? I would be happy about ldap support too :)

**Comment by emanuelschuetze** [comment]
Closed. Please reopen if you have more details for LDAP support for OS4.
