### ISSUE TITLE
Failed to access microphone on jitsi conference

### ISSUE THREAD

**Issue by datze** [OpenSlides/OpenSlides#5637]
**Describe the bug**
Users can connect to the live conference but can not activate their mic. Even not if they are the current speaker.
(see screenshots)

**How to Reproduce**

Configuration:
```
    JITSI_DOMAIN: "fairmeeting.net"
    JITSI_ROOM_PASSWORD: ""
    JITSI_ROOM_NAME: "anythingyoulike124567890987654321"
```
(same error with meet.jit.si)

1. Log in as user in group "delegate"
2. Connecto to live conference
1. Add yourself to the list of speakers
1. wait until a moderator starts your speaking time
3. Try to activate the mic

**Expected behavior**
The user should be able to activate the mic but openslides seems to prevent that. If the jitsi conference is accessed directly without openslides, activating the mic works without errors from the same browser.

**System information**

- OpenSlides-Version: latest master branch; docker-compose set-up
- Additional version information (if any): commit d2043f508cd2ec328e4a1f64946c36502a4a7b24
- Device: any (tested with several PCs and Smartphones)
- OS: any (tested with Android, Windows)
- Browser: any (tested with Chrome and FF)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11994396/96381837-73c22c00-1190-11eb-82c7-92998fc6a11d.png)

**Comment by tsiegleauq** [comment]
This is local System Error or Jitsi-Meet Error, not an OpenSlides Error. Catching the microphone works fine from OpenSlides, if your web browser is able to access it at all.

**Comment by datze** [comment]
Shouldn't OpenSlides work fine with Jitsi-Meet?

**Comment by tsiegleauq** [comment]
it does.

**Comment by datze** [comment]
didn't work for me. decided to use another solution!

**Comment by tsiegleauq** [comment]
Thats good. Did any other WebRTC Microphone access work for you? If so, you might still fail due to a configuration on your system.
In your condition, both "fairmeeting.net" and "meet.jit.si" will be third parties which require special cookie access which is often deactivated.

![image](https://user-images.githubusercontent.com/10233032/96844029-4d7de400-144f-11eb-9de5-e7a6b5302b36.png)

In any case, your issue dies not indicate a reproducible error.
