### ISSUE TITLE
Force-mute non-speakers in liveconference and give mute/unmute capability to special users/groups

### ISSUE THREAD

**Issue by jkrenzer** [OpenSlides/OpenSlides#5654]
**Is your feature request related to a problem? Please describe.**
For small virtual assemblies live streaming is overkill and often beyond the capabilities of small servers rented by smaller organizations. So you let the people join the conference for listening to the proceedings. But there is always somebody breathing or rustling into their mic and people often forgetting to mute/un-mute themselves. Also sometimes angry people disregard the speaker-list and blurt into somebodies speech. Moderation-possiblities for such incidents is quite cumbersome and incomplete in the current implementation.

**Describe the solution you'd like**
- Make this into additional options settable in the general settings
- Auto unmute the speaker when he or she gets the speech
- Auto mute all non-speakers except groups with special right (like comittee) and admin
- Button for mute/unmute  is only active for speaker
- Special permission for admin or other groups which can regardlessly mute/unmute people. For short answers or in case the client did not mute/unmute properly.
- Maybe coupled with the right to manage the speakers list.

**Describe alternatives you've considered**
- Opening up the jitsi-screen and using the mute/mute-all function does work but is cumbersome. **But** people are still able to unmute themselves or rejoing after kick, so enraged attendees ignoring the speakers list can still cause some ruckus.
- There is no possibility to unmute people remotely in standard-jitsi as this is considered a privacy-concern in a private chat setting. I think in a public assembly setting this can be considered otherwise.
- The "Only allow current speakers to join"-option does not work in this way, as all people (also past speakers) are allowed to stay in the conference and unmute themselves any time. Also there is no possibility to have people only listening, so live-streaming is necessary to achieve a somewhat working setup.

**Additional context**
None.

**Comment by tsiegleauq** [comment]
> Moderation-possiblities for such incidents is quite cumbersome and incomplete in the current implementation.

The jitsi meet client integrated in OpenSlides allows you to mute whoever interferes.

> Auto mute all non-speakers except groups with special right (like comittee) and admin

Either, nothing like that is possible or I do not know what you mean by that. By default, everyone who enters the Jitsi room over OpenSlides is muted by default. The admins can mute whoever they seem fit inside of Jitsi-Meet.

> Auto unmute the speaker when he or she gets the speech

This could probably be done, but would be high effort.

> Button for mute/unmute is only active for speaker

We cannot disable controls inside if the iFrame, all we can do from OpenSlides is to hide them under certain conditions.

> Special permission for admin or other groups which can regardlessly mute/unmute people. 

Cannot be done.

> unmute people

Will not be done. At all.

> are allowed to stay in the conference and unmute themselves any time. 

This is an issue for Jitsi, not OpenSlides

I am closing this feature request. Either, it's not an OpenSlides concern, has little value, and requests were already or can better be addressed otherwise.
