### ISSUE TITLE
Rename env var OS4_DEVELOPMENT

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5703]
Some services like the backend and the auth use an env var to provide extra debug output.

I propose to rename it from `OS4_DEVELOPMENT` to `OPENSLIDES_DEBUG`.

It is not necessary to provide the version number 4 here and in my opinion this flag is not about developing something but about debugging (during development but not exclusively).

**Comment by FinnStutzenstein** [comment]
I think `OPENSLIDES_DEVELOPMENT` is fine, since it is clearly development related: Even if you are not debugging, we need to know, that we are in development. E.g. the auth service uses dev-keys in develpment mode and the DS has features for development only (which have nothing to do with debugging).

**Comment by normanjaeckel** [comment]
Although I like `OPENSLIDES_DEBUG` better I can live with `OPENSLIDES_DEVELOPMENT`. Its still better than `OS4_DEVELOPMENT`.

**Comment by jsangmeister** [comment]
Sounds good. Will you create a PR for backend and auth service?

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/openslides-backend/pull/318

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/openslides-auth-service/pull/50

**Comment by FinnStutzenstein** [comment]
Is it done?

**Comment by normanjaeckel** [comment]
Yes.
