### ISSUE TITLE
SMTP AUTH extension not supported by server.

### ISSUE THREAD

**Issue by github-luckow-org** [OpenSlides/OpenSlides#5710]
**Describe the bug**
The attempt to send the password reset mail results in the following log entry:

`
server_1          | [2020-11-18 15:10:47 +0100] [42] [WARNING] openslides.requests.errors [fseL] /apps/users/reset-password/ 0 unknown exception: SMTP AUTH extension not supported by server.
server_1          | [2020-11-18 15:10:47 +0100] [42] [ERROR] django.request Internal Server Error: /apps/users/reset-password/
`
**How to Reproduce**
Insert your smtp credentials into .env file. In my case it's a tls based smtp connection. 
Start the docker containers. 
Click on Forgot Password? 
Look at the log file.

**Expected behavior**
Sending emails via SMTP Auth should work. 

**System information**

- OpenSlides-Version: 3.2
- Additional version information (if any): docker

**Comment by BrutalBirdie** [comment]
Adding Log

```
server_1          | [2020-11-18 16:06:12 +0100] [37] [WARNING] openslides.requests.errors [mvKe] /apps/users/reset-password/ 0 unknown exception: SMTP AUTH extension not supported by server.
server_1          | [2020-11-18 16:06:12 +0100] [37] [ERROR] django.request Internal Server Error: /apps/users/reset-password/
server_1          | Traceback (most recent call last):
server_1          |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
server_1          |     response = get_response(request)
server_1          |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
server_1          |     response = self.process_exception_by_middleware(e, request)
server_1          |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
server_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
server_1          |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
server_1          |     return view_func(*args, **kwargs)
server_1          |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
server_1          |     return self.dispatch(request, *args, **kwargs)
server_1          |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
server_1          |     response = self.handle_exception(exc)
server_1          |   File "/app/openslides/utils/rest_api.py", line 145, in handle_exception
server_1          |     return super().handle_exception(exc)  # type: ignore
server_1          |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
server_1          |     self.raise_uncaught_exception(exc)
server_1          |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
server_1          |     response = handler(request, *args, **kwargs)
server_1          |   File "/app/openslides/users/views.py", line 1054, in post
server_1          |     email_message.send()
server_1          |   File "/usr/local/lib/python3.7/site-packages/django/core/mail/message.py", line 306, in send
server_1          |     return self.get_connection(fail_silently).send_messages([self])
server_1          |   File "/usr/local/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
server_1          |     new_conn_created = self.open()
server_1          |   File "/usr/local/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 70, in open
server_1          |     self.connection.login(self.username, self.password)
server_1          |   File "/usr/local/lib/python3.7/smtplib.py", line 697, in login
server_1          |     "SMTP AUTH extension not supported by server.")
server_1          | smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
```
.env excerpt
```bash
# cat .env | grep -i mail
# E-Mail
DEFAULT_FROM_EMAIL=openslides@domain.tld
EMAIL_HOST=mail.domain.tld
EMAIL_HOST_PASSWORD=did_you_really_think_i_leave_a_password_here_?
EMAIL_HOST_USER=openslides@domain.tld
EMAIL_PORT=587
EMAIL_USE_SSL=
EMAIL_USE_TLS=True
EMAIL_TIMEOUT=
```

I can confirm that these settings work for different software project with the exact same settings.

**Comment by FinnStutzenstein** [comment]
@gsiv I'm not sure, if we can do something about it?

**Comment by gsiv** [comment]
Personally, due to the error message, I would be looking for the problem on the mail server.  @BrutalBirdie, could you provide the mail server log from one such connection attempt?

It would also be interesting to try to manually send email through the same mail server from the container, e.g., using swaks.

If we rule out mail server issues, it becomes a question about `smtplib` and, I'm afraid, I'm not the right person to look into that.

**Comment by Gravity-87** [comment]
I ran in the same problem, sending E-Mail via OpenSlides with an external mail host. The trick, that made sending e-mail possible for me, was:

- Go to your: docker-compose.yml
- Go to the e-mail section of the server, where are the settings like the above e-mail settings (they are so far correct! I used similar ones...)
- And now: Insert the following line near the e-mail section:
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"

- stop your docker container
- in the directory of your OpenSlides sources (../OpenSlides/docker) build the (docker) server new (in my case) with: 
$ ./build.sh server (or if you want so, all with: ./build.sh all - but I think it's not necessary...)
- start your docker container

If you don't want tu use the SMTP backend of Django, you can use a so called "Console backend" for testing purposes...

Perhaps have a look for this issue at:
https://docs.djangoproject.com/en/2.2/topics/email/#smtp-backend

But, beware just copying the needed lines from that page, because there is for instance:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

This original line from the Doc-page didn't work for - I got typo-errors. So, perhaps pay attention, that the '=' is substituted by ':' in the docker.yml-file. This worked for me at the end.

Hope this will help.

**Comment by FinnStutzenstein** [comment]
Setting `EMAIL_BACKEND` should not be needed since it is already there: https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/global_settings.py#L59

Which version of OpenSlides are you using?

**Comment by Gravity-87** [comment]
@FinnStutzenstein 
In my changelog file of OpenSlides (got it from Github) the last entry is:
'Version 3.3 (2020-12-18)'

**Comment by FinnStutzenstein** [comment]
Ok. Entering `EMAIL_BACKEND` in the `.env` or `docker-compose.yml` should not make a difference: This is the place the settings are loaded from the environment: https://github.com/OpenSlides/OpenSlides/blob/master/server/docker/settings.py. There is no occurrence of `EMAIL_BACKEND`. I'm not sure that what you have done fixed it. Maybe try to remove it.

Also maybe update your docker images by building them again, maybe they are outdated.

**Comment by jsangmeister** [comment]
OpenSlides3 is no longer maintained.
