### ISSUE TITLE
Rename default branch from master to main.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5829]
See https://github.com/OpenSlides/openslides-backend/issues/287

We should do this in all active repositories.

**Comment by tsiegleauq** [comment]
why?

**Comment by normanjaeckel** [comment]
Among many others the [Software Freedom Conservancy is promoting this issue](https://sfconservancy.org/news/2020/jun/23/gitbranchname/). GitHub has [taken this path](https://github.com/github/renaming) as well. I think that also the OpenSlides community can make this step to use a less offensive language.

**Comment by normanjaeckel** [comment]
The renaming can be easily done before or after next code sprint and maybe together with any new branch strategy (to prevent accidents when new features are developed simultaneously).

**Comment by tsiegleauq** [comment]
Mainly @gsiv would have to acknowledge the changes since he takes care of our deployment.
I don't really care if I rebase to /master or /main. I would prefer main for the reason that it's just shorter and closer to the way I explain Git to people (like "master is your main branch").
Over all possible terms, I'd prefer "stable" but this would be a lie :-P

**Comment by gsiv** [comment]
> Mainly @gsiv would have to acknowledge the changes since he takes care of our deployment.

Thanks, acknowledged.  It doesn't make a difference to me either.

**Comment by jsangmeister** [comment]
done for media service
