### ISSUE TITLE
OpenSlides is not displayed in the browser

### ISSUE THREAD

**Issue by blinky0110** [OpenSlides/OpenSlides#5846]
Hello everybody.

I'm new to Linux.

I installed openslides as described. After I created the container with docker-compose up, the server could be started, but no opensliders are displayed in the browser.

I'll copy your logs in. If you need more information, please let me know.

[error.txt](https://github.com/OpenSlides/OpenSlides/files/5921914/error.txt)

**Comment by FinnStutzenstein** [comment]
Which url did you try? For a default setup it is https://localhost:8000

Elsewise @gsiv please have a look in the logs. The pgnode seems to be fine first (migrations ran correctly, so there must be something), but at the end there is a `[ERROR] connection to database failed:` which seems suspicious.

**Comment by blinky0110** [comment]
I used the ip address from the vserver followed by the port.

It worked with an earlier installation via pip3.

Since I am inexperienced with Linux, I would be grateful for your advice.

**Comment by gsiv** [comment]
> Elsewise @gsiv please have a look in the logs.

The logs are out of order, so I'm looking at the services individually.  From what I can tell, everything was working just fine.

> but at the end there is a `[ERROR] connection to database failed:` which seems suspicious.

This can be expected as part of the of the database container's setup process because supervisord starts multiple services at once.  (That is not to say that it couldn't be improved!  Help would be welcome.)

> Which url did you try? For a default setup it is https://localhost:8000

I assume this is the explanation.  To expose the instance directly on your server you would need to edit `docker-compose.yml` and replace `127.0.0.1` with, e.g., `0.0.0.0`.  I would advise against that, however.  Instead, you should consider using a reverse proxy on your server to handle the internet-facing traffic.

**Comment by FinnStutzenstein** [comment]
Right, regardless of the database, the client must be delivered. So if you get no response or whatever when trying to reach OpenSlides, it indicates that the request is not accpted by the haproxy

**Comment by blinky0110** [comment]
I turned to the support from the server. They informed me that Docker is not fully supported on the server.

Many thanks for your help.

Since the installation via pip works and works, are there any security concerns?

**Comment by FinnStutzenstein** [comment]
The current version of OpenSLides does not support pip anymore. It is clearly advised to update, e.g. due to security issues (e.g. https://github.com/OpenSlides/OpenSlides/security/advisories/GHSA-w5wr-98qm-jx92)

**Comment by tsiegleauq** [comment]
not an issue. Inactive. Closing.
