### ISSUE TITLE
cannot run ./build.sh all on macOS

### ISSUE THREAD

**Issue by manuel-mauky** [OpenSlides/OpenSlides#6126]
**Describe the bug**
I'm trying to run `./build.sh all` but it prints errors.

**How to Reproduce**
1. clone the repository (including submodules) like described in README
2. `cd docker`
3. `./build.sh all`
4. I get 
```
> ./build.sh all
ERROR: Cannot build hr:D:t:: not configured.
ERROR: Cannot build -l: not configured.
ERROR: Cannot build help,docker-repo:,tag:,ask-push,no-cache: not configured.
ERROR: Cannot build -n: not configured.
ERROR: Cannot build --: not configured.
ERROR: Cannot build all: not configured.
No images were built.
```

**System information**

- OpenSlides-Version: current master branch
- Python Version: 3.8.2
- Device: Macbook Pro
- OS: Mac OS 10.15.7
- docker: 20.10.7
- docker-compose: 1.29.2

**Comment by gsiv** [comment]
This is probably due to an incompatible version of getopt on OS X.  There was a similar report here: https://github.com/OpenSlides/OpenSlides/pull/5805.

My understanding is that you could install GNU getopt on OS X using brew et al.

Clearly, the way the situation is handled by the script leaves a lot to be desired though.  Thanks for the report.

**Comment by tsiegleauq** [comment]
> My understanding is that you could install GNU getopt on OS X using brew et al.

It would be helpful if somebody who is running macOS could confirm that OpenSlides can be build using GNU getopt, so we can adjust out build information for macOS

**Comment by manuel-mauky** [comment]
I can verify that it works with getopt.
I've done
```
brew install gnu-getopt
```
and after adding the installed getopt executable to the $PATH, the build script now works as expected.
