### ISSUE TITLE
Jitsi Error in Chrome based browser when joining jitsi-meeting in iframe

### ISSUE THREAD

**Issue by YveIce** [OpenSlides/OpenSlides#6402]
**Describe the bug**
When clicking on the phone symbol to connect to the jitsi-meeting, chrome based browser like chrome, brave, edge hangs many (on most trys) in a loading loop or throw error:
_TypeError: Cannot destructure property 'id' of 'Yb(...)' as it is undefined._ in webpack://jitsi-meet/conference.js Line: 3146
```js
    changeLocalDisplayName(nickname = '') {
        const formattedNickname = getNormalizedDisplayName(nickname);
        const { id, name } = getLocalParticipant(APP.store.getState()); /* <== ERROR THROWN HERE */

        if (formattedNickname === name) {
            return;
        }

        APP.store.dispatch(participantUpdated({
            // XXX Only the local participant is allowed to update without
            // stating the JitsiConference instance (i.e. participant property
            // `conference` for a remote participant) because the local
            // participant is uniquely identified by the very fact that there is
            // only one local participant.

            id,
            local: true,
            name: formattedNickname
        }));

        APP.store.dispatch(updateSettings({
            displayName: formattedNickname
        }));
    },
```

**How to Reproduce**
 - Setup a openslides 3.4.x with jitsi meeting configured
 - try to connect to the jitsi-meeting by clicking on the phone symbol

**Expected behavior**
 should open the jitsi iframe window with out issues

**System information**

- OpenSlides-Version: 3.4.x [1b2169d](https://github.com/OpenSlides/OpenSlides/commit/1b2169dd45e23cdb03b97c217d3544b3634b816f)
- Browser: brave, chrome, edge
- Browser-Version: chromium 100.0.4896.88.

**Additional context**
i dig a little bit in the issue. For me, it seams that in [/client/src/app/site/interaction/services/rtc.service.ts#L254](https://github.com/OpenSlides/OpenSlides/blob/420bef680a4c76c07cd9c57a26be13b08ee8c37d/client/src/app/site/interaction/services/rtc.service.ts#L254)
```js
this.api.executeCommand('displayName', jitsiName);
```
is called, before a LocalParticipant is created on the jitsi side. 

For me the issue can be fixed like this: 
 [/client/src/app/site/interaction/services/rtc.service.ts#L253](https://github.com/OpenSlides/OpenSlides/blob/420bef680a4c76c07cd9c57a26be13b08ee8c37d/client/src/app/site/interaction/services/rtc.service.ts#L253)
 ```diff
-        const jitsiName = this.operator.viewUser.getShortName();
-        this.api.executeCommand('displayName', jitsiName);
 ```
[/client/src/app/site/interaction/services/rtc.service.ts#L384](https://github.com/OpenSlides/OpenSlides/blob/420bef680a4c76c07cd9c57a26be13b08ee8c37d/client/src/app/site/interaction/services/rtc.service.ts#L384) 
 ```diff
    private setOptions(): void {
        this.setJitsiMeetUrl();
+      const jitsiName = this.operator.viewUser.getShortName();
        this.options = {
            roomName: this.actualRoomName,
            parentNode: this.jitsiNode.nativeElement,
            configOverwrite: configOverwrite,
-            interfaceConfigOverwrite: interfaceConfigOverwrite
+            interfaceConfigOverwrite: interfaceConfigOverwrite,
+            userInfo: {
+                displayName: jitsiName
+            }
        };
    }
``` 

_I don't want to make a PR, as my experience level with nodejs, react and co is: noob_ ;-)

**Comment by jsangmeister** [comment]
I can reproduce the bug (although for me, the infinite spinner appears every time and I don't get any error message at all) and implemented you proposed fix on my fork: https://github.com/jsangmeister/OpenSlides/tree/jitsi-bug. Unfortunately, it does not seem to help and the bug persists.

Since this bug does not occur in OS4 (https://demo.os4.openslides.com/) and we are not actively working on OS3 anymore, we will probably no investigate this further. But please feel free to debug this problem and maybe find a fix for it, we will be more than happy to include it in a future bug fix release. To develop in OS3, just check out the branch and run `make run-dev` as described in https://github.com/OpenSlides/OpenSlides/blob/stable/3.4.x/DEVELOPMENT.rst. Afterwards, you can access your local instance on https://localhost:8000/, where you can experiment with it. Make sure to set the Jitsi variables under `server/personal_data/var/settings.py` and restarting the server afterwards (`make stop-dev` -> `make run-dev`) to have jitsi available. Feel free to ask questions if any come up.

**Comment by YveIce** [comment]
For me, in OS4 the same Error occur. [https://demo.os4.openslides.com/7](https://demo.os4.openslides.com/7)
Quick look in the code, shows me, that it's equal on this part to OS 3.4
(On this demo side and in our own test, applaus also not works for example. So OS4 is no choice for us, right now).  
I got my patch running live, and on our side it fixed the problem. 
(Try to test it in a private tab)

**Comment by YveIce** [comment]
Fixed with: https://github.com/OpenSlides/openslides-client/pull/1573
