### ISSUE TITLE
Diable Caching in Settings

### ISSUE THREAD

**Issue by nevyen** [OpenSlides/OpenSlides#6658]
**Is your feature request related to a problem? Please describe.**
We copy our online instance to a local server to host openslides in a local network. 
Often we are at locations where the Internet connection is not so fast. Thats the reason why we choose this step. 
The Problem then is, that the cache of OpenSlides leads to an difficult behaviour. Often OpenSlides loads an old version. 

**Describe the solution you'd like**
Create a setting where we can disable the caching.

**Comment by jsangmeister** [comment]
What caching do you mean exactly? Client-side or server side? Which services exactly were the problem? We need some more details to help you.

**Comment by nevyen** [comment]
I mean the client side caching. 

The main problem was to login aiganst the local OpenSlides. Most People tried to login again the online OpenSlides.

Another problem was, that some people didn't see anything as the autopilot. 
But we found no way to reconstruct this problem. First it seems to be the browser. But then it happens in the same browser it works on other clients.

**Comment by jsangmeister** [comment]
Unfortunately, I don't think this is a feasible feature. Asides from the fact that the browser itself does some caching which is hard to control, it is a very specific situation and would probably require a lot of work to implement correctly. As a workaround, you can try to clear all application data (for example in chrome: F12->Application->Clear site data) in the problematic browsers. this should clear all OpenSlides-specific caches etc. and also unregister all service workers. Then after a reload, everything should be working correctly or otherwise it's another problem besides the caching.
