### ISSUE TITLE
OS 4.1 Postgres 15 update docs are not working

### ISSUE THREAD

**Issue by depate** [OpenSlides/OpenSlides#6740]
**Describe the bug**

The update routine is not working as described in the docs or a crucial part is missing.

**How to Reproduce**

Follow the "How to update routine" for `4.1`.

Dump the database ✅ 
Update as documented ✅ (fix the new tag, pull, start up the containers),
Start containers 🔴 
The mentioned database error appears.
The database container shuts down, so a restore is not possible. 
Deadlock.

**Expected behavior**

Somewhere I database migration/upgrade is taking place.

**Additional context**

The docs don't say how the database is upgraded. The docs also say the “old” `openslides` tool shall fix a missed database dump, but don't really tell how and for me, it doesn't make any sense, because the tool is not involved in dumping or restoring at all.

**Screenshots**

Please fix the docs.

Did anybody test these steps in the docs manually or via CI? 🤔 

The merge responsible is: https://github.com/OpenSlides/OpenSlides/pull/6711

Merged by @rrenkert, introduced by @peb-adr

**Comment by depate** [comment]
I settled on `4.0.17` as this is the latest version before `4.1`.

**Comment by peb-adr** [comment]
I'm sorry to hear the update didn't work for you.

It seems like I forgot to include the step of removing the `postgres-data` volume in the instructions.

So basically just running `docker-compose down -v` before starting containers with the new images was missing.\
However now I expanded the instructions to hopefully also be more safe and clear about potential data loss.


I think for some reason I was under the impression that, because the dump is done with `--clean` it would take care of once removing all data and then reinserting it. It seems I did not think/test that through til the end.

Sorry for the inconvenience.\
I updated the doc in #6741\
Could you please test it and verify that it is now possible to perform the update?
