### ISSUE TITLE
Remove the need for openslides manage tool for initial-data

### ISSUE THREAD

**Issue by InterFelix** [OpenSlides/OpenSlides#6745]
**Is your feature request related to a problem? Please describe.**
I'm trying to integrate OpenSlides into a collection of Ansible playbooks.
However, it's impossible to achieve true idempotency with the roles I've written so far, as the openslides manage tool needs to be executed in order to create a functional instance of openslides, and the execution of `openslides initial-data` is not idempotent if my understanding is correct.

**Describe the solution you'd like**
Remove the need for `openslides initial-data` during the installation process

**Describe alternatives you've considered**
An idempotent implementation of `openslides inital-data` with clearly documented exit-codes (e.g. 0 -> nothing changed, initial data already existed; 1 -> initial data loaded; 2 -> error of some kind) would solve my specific problem as well.
However, the current setup process is impractical for other method of infrastructure automation as well. For example, building a helm chart for OpenSlides is made extremely challenging by the need to execute the manage tool in order to create a functional instance of OpenSlides.

**Comment by jsangmeister** [comment]
Hi, thanks for your suggestion! We've noticed this problem internally as well and decided to now fix it. In https://github.com/OpenSlides/openslides-backend/pull/2295 I moved the functionality to the backend, which simply inserts the initial data on startup instead of requiring an extra command. We will update the relevant README sections shortly and plan to include this in version 4.1.4 (since 4.1.3 is currently in testing and will release shortly).
