### ISSUE TITLE
Meetings > new access restriction: Lock participants out of a meeting

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/OpenSlides#6756]
Description: Integrate a new option to lock out participants from a meeting. The participants will stay inside the meeting, but they can't see it in the Dashboard and they also can't enter it by URL. The administration of this should be done by meeting admins.

**Comment by ostcar** [comment]
I moved this to the main reqo. Most of the work has to be done in the autoupdate-repo, but there are also required changes in the client, meta and backend repo.

**Comment by ostcar** [comment]
At the moment, the feature is not clear to me. Do you want to lock single users or groups of users? For example, if the meeting has 10.000 participants. Do you want to lock 3 users, or do you want to lock out some groups (delegates, guest, etc).

Another question is, what should happen, if a user is locked out of a meeting, but anonymous is enabled in the meeting. I would say, an locked out user has the same permissions in the meeting, as an anonymous user.

What about global permissions. If a user with the OML-can_manage_users is locked out? The restrictor depends often on this permission. What about the CML-can_manage and the permissions, that participants of a committee have for all the meetings?

What if a meeting-admin is locked out? (why would someone do this, but what should the code do in this case?)

If you want to lock out groups, then I would propose, that we add a "deactivated" flag to the group collection. To calculate the permissions of a user, groups that are deactivated are ignored. Also, deactivated groups do not count for the question, [if a user is a particimant of a meeting](https://github.com/OpenSlides/OpenSlides/wiki/Users#user-association-to-meetings).

This would be easy to implement.

If you want to lockout single users, then I would still solve this via the permissions. If a user is in the (new) field `meeting/locked_out_user_ids`, he has no permission in the meeting (or only the same permissions as anonymous). The definition of a participant would be, that a user is part of a meeting, if he is in a group of that meeting and not in the list `meeting/locked_out_users`.

I would prefer, that we solve this via the groups. But the ABS team has to tell us, what the usecaes is.


This issue is relevant in a lot of places in the restrictor. Here some examples:

* The restricter often gives permissions, if a user is in a specific group (chat_message, media_files, motion_comment_section, motion_comment, etc).
* Some checks are agains a against a user ID (for example personal_note).

**Comment by jsangmeister** [comment]
> If a user is in the (new) field `meeting/locked_out_user_ids`, he has no permission in the meeting (or only the same permissions as anonymous).

This is the behaviour we currently have for the presence of users ( `meeting/present_user_ids`<->`user/is_present_in_meeting_ids`) and it's not a very clean solution. Since we have the n:m model `meeting_user`, we should use it to model any relevant information regarding a user in a meeting. So, my proposal would be to introduce a new boolean `meeting_user/is_deactivated` (or similar), which locks a user out if it's true. This should be just as easy to check for the restrictor since the `meeting_user` has to be read anyway because of the group ids and it's a cleaner model.

As I understood it, the locking of single users is alos how it the feature was intended, but we'll wait for confirmation from the ABS team.

**Comment by MSoeb** [comment]
We need to clearify:

- [ ] how should this be handled by users/admins
- [ ] from this point, we should discuss a technical solution

**Comment by Elblinator** [comment]
I'll write down some notes summarising this discussion, the official necessities, a discussion with @rrenkert and small discussions here and there. Everything besides the requirements can be discussed/changed and need the green light from one or more person. Issues will be created/updated accordingly. 

I will also edit this comment if some answers become clear

**Clear requirements:**
- If locked out the participant is still in the meeting
- If locked out the participant cannot see or navigate via url to the meeting
- A single participant (independent from group) can be locked out
- A new filter/sort should be added in the participant-list

**Questions which need clarification and some already gathered thoughts about them (some questions need a discussion some questions just need a yes/no):**
- Who can lock participants out (which permission/group)?
      -> So far consensus: Admins can lock participants out, no defined permission is needed but the people from the admin group can lock out
- Who can see that a participant is locked out? (Permission candidates are user.canSee/canSeesensitiveData/CanManage
- models.yml needs a new field: would a new field ```is_locked_out``` which is similar to ```is_active``` suffice?
- Who can be locked out? (So far consensus):
    - You (you lock yourself out)
         - No
    - (Meeting-) Admins
         - No
         - Theoretically we can strip them from their group and then lock them out
    -  Superadmins
         - No, is that even possible?
    - Orgaadmins
         - Yes
    - Accountadmins
         - Yes
    - Committeeadmins
         - Yes
    - Every User in a meeting who does not fall under the groups above
         - Yes
- What should happen if a participant who is locked out becomes an admin?
    - Option 1: The participant is automatically not locked out anymore 
    - Option 2: You are warned by a dialog that this will lift the lockout and the participant is automatically not locked out anymore 
    - Option 3: You are warned that this is a locked out participant and you cannot give this participant admin right until you lift the lock out first
    - Indirect consequence: Admins **CAN NEVER** be locked out 
- This action should be possible via participant detail view and the multi-select in the participant view (mass locking out is allowed)
- How should the multi-select be handled if you try to do something forbidden (lock out admin or make someone locked out admin)?
   - Hint: The client is not checking whether or not locked out/admins are selected in multi-select, this was discussed in the past, so the errors thrown and actions done have to come from the backend
   - if you try to lock out admins: 
       -  Should the whole action be stopped with an Error similar to ```You are trying to lock out an admin, please remove admins from the lock out list)```
       - Should only the allowed participants be locked out? 
       - If yes, how should the system inform about the participants which were not successfully locked out
           - Generic: ```There were admins, They cannot be locked out so they were skipped```
           - Specific: ```The following participants were not locked out due to them being admins: ....``` -> worst case: this will be shown in a snackbar, and the snackbar could be ginormous
       - Theoretically we can also decide to strip the admins from their admin group if you lock them out, I would recommend a big warning if we would decide to follow this logic though, this warning has to always be shown in the dialog (because the client is not checking if there are admin in the selected participants
    - if you try make someone locked out an admin: 
       - Should the dialog have an additional button which forces every participant to be not locked out anymore and then successfully become an admin? and if the normal button is used admins are skipped (where and how should this be explained)
       - Should the dialog (without additional button) just lift the lock out and turn them into admins?
       - Should the whole action be stopped with an Error similar to ```You are trying to assign someone locked out the  admin group, please remove locked out users from this action)```
       - Should only the allowed participants become admins? 
       - If yes, how should the system inform about the participants which did not successfully become admins
           - Generic: ```There were locked out users, they cannot become admins so they were skipped```
           - Specific: ```The following participants did not become admins due to them being locked out: ....``` -> worst case: this will be shown in a snackbar, and the snackbar could be ginormous
- View in the future context anonymous user: 
   -  How should anonymous user and a locked user be handled:
       - Should we prohibit locked out users in an opened meeting and vise verse prohibit a meeting with locked out users to be open?
       - Should we show the (logged in) participant the same amount of information an anonymous user would see
       - Should we show the (logged in) participant nothing and if they log out they can see the meeting
           - This last question is also relevant in general for anonymous user, because we need to clarify what a participant user can see in they are logged in but are not a participant of an open meeting
      -  We don't need to fix the answers to the anonymous user now and here (this belongs in the anonymous user debate) but a rough idea and debate at this place would be useful

**Comment by Elblinator** [comment]
The mock-up for the new feature 
- The red is supposed to be the warn colour
- The function of is_active did not change the placment was just moved unter the present checkbox
- The checkbox for locking_out is supposed to be in the three dot menu, only the indicator is outside

The appearance for the mobile view is still missing and further information will be updated (probably in the client issue)
![inaktiv_ausgeschlossen](https://github.com/OpenSlides/OpenSlides/assets/69210919/5840371e-1386-4e69-ba61-240f4c2b6f8a)

**Comment by MSoeb** [comment]
Feature is done.
