### ISSUE TITLE
Client goes into Fallback Mode

### ISSUE THREAD

**Issue by kempert** [OpenSlides/OpenSlides#6780]
We are using Openslides in a Standart Config (Port), AutoLocalHTTPS: true AutoHTTPS:true.
Behind a ngnix Proxy Manager.

We habe the Problem that the Client at Phone oder Browser, Not respond by clicking a the First event. After some Times, a Blue Banner Fallback Mode comes up, and it works, but only in Fallback Mode.

Can Anyone Help us?

**Comment by Elblinator** [comment]
Your proxy is probably creating the problem here:
The stream from the autoupdate is continuously open, 
The proxy however wants a closed off update.
The fallback mode is exactly allowing that: it gets a closed off package from the autoupdate, confirming whatever it wants to confirm and then updates the site.

The fallback mode has a delay of ~5 seconds.
If you want to use the normal mode and have no delay at all, you need to allow the continuously opened stream from the autoupdate.

@kempert What is your nginx config? Maybe something in there prevents the autoupdate stream

**Comment by Elblinator** [comment]
your pfsense could interject the http2 stream and hence be the reason why the autoupdate is blocked

Can you try deactivating pfsense and/or try accessing your instance via your internal network. Is it still going into the Fallback Mode then?

**Comment by kempert** [comment]
Hi, over Internal network with IP are no Problems. In the pfSense noting at 443 or 80 is blocked, it ist only NAT to the Ngnix Proxy.
Is there any Ngnix Proxy Option? Also Internal Networking (DNS -> Ngnix -> Openslide) goes in the Fallback mode, then is no pfsense in the Routing.

**Comment by kempert** [comment]
Hello,

after researching i have found a soulution. Adding "proxy_buffering off;" is the Solution.

![image](https://github.com/OpenSlides/OpenSlides/assets/51061932/dda28dc5-5b58-4c14-a496-7b8a1728aa36)

Greetings, and thanks for the Reason,
