### ISSUE TITLE
Error message on Motions page, unexpected "Add" button

### ISSUE THREAD

**Issue by mdickopp** [OpenSlides/OpenSlides#6828]
**Describe the bug**

When a user without "Can create motions" and with "Can create amendments" permissions opens the Motions page, an error message is displayed. Furthermore, the "Add" ("+" in a circle) button is displayed, although the user does not have the permission to add motions.
 
**How to Reproduce**

1. Install OpenSlides according to `INSTALL.md`.
2. As superuser, create a committee and a meeting.
3. Set permissions so that the default group does not have the "Can create motions" permission and does have the "Can create amendments" permission (see screenshot below).
4. Add a motion.
5. Add a user in the default group.
6. Log out and log in as the user in the default group.
7. Open the meeting.
8. Go to the Motions page.
9. Observe error message and "Add" button (see screenshot below)

**Expected behavior**

- No error message is displayed
- "Add" ("+" in a circle) button is not displayed

**System information**

- OpenSlides version: 4.1.18 (2024-10-17) 
- Additional version information (if any): -
- Device: Desktop PC
- OS: Debian Linux 12.7
- Browser: Firefox
- Browser version: 131.0.3

**Screenshots**

Permission settings:

![Permission settings](https://github.com/user-attachments/assets/a17360be-5395-40a3-bd10-4611c92b92cf)

Motions page with error message and "Add" button:

![Motions page with error message and "Add" button](https://github.com/user-attachments/assets/9d8a1f84-311a-4540-8fe0-38bcc5603891)

**Comment by Elblinator** [comment]
The Bug you are describing is already known: https://github.com/OpenSlides/openslides-client/issues/4108
The gist of this bug is that if you were logged in with a user with more group rights then you can still see all the buttons from this user even if you log in as someone with less rights. 
The user with less rights can still not use these buttons and they also only get the information they are allowed to see. 
The problem (visibly) occurs if you are allowed to see the same pages (e.g. motion-list)

Thanks to your report we however found a different bug, where a user can only create amendments if they are allowed to create motions:
https://github.com/OpenSlides/openslides-client/issues/4275

Thanks for the report
